// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveEnvironmentBuffStateHandle : RemoteTableHandle<EventContext, ActiveEnvironmentBuffState>
        {
            protected override string RemoteTableName => "active_environment_buff_state";

            public sealed class PlayerBuffIndex : BTreeIndexBase<(ulong EntityId, int BuffId)>
            {
                protected override (ulong EntityId, int BuffId) GetKey(ActiveEnvironmentBuffState row) => (row.EntityId, row.BuffId);

                public PlayerBuffIndex(ActiveEnvironmentBuffStateHandle table) : base(table) { }
            }

            public readonly PlayerBuffIndex PlayerBuff;

            public sealed class EntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveEnvironmentBuffState row) => row.EntityId;

                public EntityIdIndex(ActiveEnvironmentBuffStateHandle table) : base(table) { }
            }

            public readonly EntityIdIndex EntityId;

            internal ActiveEnvironmentBuffStateHandle(DbConnection conn) : base(conn)
            {
                PlayerBuff = new(this);
                EntityId = new(this);
            }
        }

        public readonly ActiveEnvironmentBuffStateHandle ActiveEnvironmentBuffState;
    }
}
