// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BarterStallInventoryEventHandle : RemoteEventTableHandle<EventContext, BarterStallInventoryEvent>
        {
            public override string RemoteTableName => "barter_stall_inventory_event";

            internal BarterStallInventoryEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly BarterStallInventoryEventHandle BarterStallInventoryEvent;
    }

    public sealed class BarterStallInventoryEventCols
    {
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong> ShopEntityId { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong> ClaimEntityId { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong> ActorEntityId { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, BarterStallInventoryChangeReason> Reason { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong> TradeOrderEntityId { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, int> TradeAmount { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, System.Collections.Generic.List<ItemStack>> AddedItems { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, System.Collections.Generic.List<ItemStack>> RemovedItems { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, int> TreasuryCoinsAdded { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, int> TreasuryCoinsRemoved { get; }
        public global::SpacetimeDB.Col<BarterStallInventoryEvent, SpacetimeDB.Timestamp> Timestamp { get; }

        public BarterStallInventoryEventCols(string tableName)
        {
            ShopEntityId = new global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong>(tableName, "shop_entity_id");
            ClaimEntityId = new global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong>(tableName, "claim_entity_id");
            ActorEntityId = new global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong>(tableName, "actor_entity_id");
            Reason = new global::SpacetimeDB.Col<BarterStallInventoryEvent, BarterStallInventoryChangeReason>(tableName, "reason");
            TradeOrderEntityId = new global::SpacetimeDB.Col<BarterStallInventoryEvent, ulong>(tableName, "trade_order_entity_id");
            TradeAmount = new global::SpacetimeDB.Col<BarterStallInventoryEvent, int>(tableName, "trade_amount");
            AddedItems = new global::SpacetimeDB.Col<BarterStallInventoryEvent, System.Collections.Generic.List<ItemStack>>(tableName, "added_items");
            RemovedItems = new global::SpacetimeDB.Col<BarterStallInventoryEvent, System.Collections.Generic.List<ItemStack>>(tableName, "removed_items");
            TreasuryCoinsAdded = new global::SpacetimeDB.Col<BarterStallInventoryEvent, int>(tableName, "treasury_coins_added");
            TreasuryCoinsRemoved = new global::SpacetimeDB.Col<BarterStallInventoryEvent, int>(tableName, "treasury_coins_removed");
            Timestamp = new global::SpacetimeDB.Col<BarterStallInventoryEvent, SpacetimeDB.Timestamp>(tableName, "timestamp");
        }
    }

    public sealed class BarterStallInventoryEventIxCols
    {

        public BarterStallInventoryEventIxCols(string tableName)
        {
        }
    }
}
