// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimLowercaseNameStateHandle : RemoteTableHandle<EventContext, ClaimLowercaseNameState>
        {
            protected override string RemoteTableName => "claim_lowercase_name_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimLowercaseNameState row) => row.EntityId;

                public EntityIdUniqueIndex(ClaimLowercaseNameStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class NameLowercaseUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ClaimLowercaseNameState row) => row.NameLowercase;

                public NameLowercaseUniqueIndex(ClaimLowercaseNameStateHandle table) : base(table) { }
            }

            public readonly NameLowercaseUniqueIndex NameLowercase;

            internal ClaimLowercaseNameStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                NameLowercase = new(this);
            }

            protected override object GetPrimaryKey(ClaimLowercaseNameState row) => row.EntityId;
        }

        public readonly ClaimLowercaseNameStateHandle ClaimLowercaseNameState;
    }
}
