// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CraftContinueStartEventHandle : RemoteEventTableHandle<EventContext, CraftContinueStartEvent>
        {
            public override string RemoteTableName => "craft_continue_start_event";

            internal CraftContinueStartEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly CraftContinueStartEventHandle CraftContinueStartEvent;
    }

    public sealed class CraftContinueStartEventCols
    {
        public global::SpacetimeDB.Col<CraftContinueStartEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<CraftContinueStartEvent, PlayerCraftContinueRequest> Request { get; }

        public CraftContinueStartEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<CraftContinueStartEvent, ulong>(tableName, "actor_id");
            Request = new global::SpacetimeDB.Col<CraftContinueStartEvent, PlayerCraftContinueRequest>(tableName, "request");
        }
    }

    public sealed class CraftContinueStartEventIxCols
    {

        public CraftContinueStartEventIxCols(string tableName)
        {
        }
    }
}
