// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeployableDisembarkEventHandle : RemoteTableHandle<EventContext, DeployableDisembarkEvent>
        {
            protected override string RemoteTableName => "deployable_disembark_event";

            internal DeployableDisembarkEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly DeployableDisembarkEventHandle DeployableDisembarkEvent;
    }

    public sealed class DeployableDisembarkEventCols
    {
        public global::SpacetimeDB.Col<DeployableDisembarkEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<DeployableDisembarkEvent, ulong> DeployableEntityId { get; }

        public DeployableDisembarkEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<DeployableDisembarkEvent, ulong>(tableName, "actor_id");
            DeployableEntityId = new global::SpacetimeDB.Col<DeployableDisembarkEvent, ulong>(tableName, "deployable_entity_id");
        }
    }

    public sealed class DeployableDisembarkEventIxCols
    {

        public DeployableDisembarkEventIxCols(string tableName)
        {
        }
    }
}
