// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeployableDeployStartEventHandle : RemoteEventTableHandle<EventContext, DeployableDeployStartEvent>
        {
            public override string RemoteTableName => "deployable_deploy_start_event";

            internal DeployableDeployStartEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly DeployableDeployStartEventHandle DeployableDeployStartEvent;
    }

    public sealed class DeployableDeployStartEventCols
    {
        public global::SpacetimeDB.Col<DeployableDeployStartEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<DeployableDeployStartEvent, DeployableDeployRequest> Request { get; }

        public DeployableDeployStartEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<DeployableDeployStartEvent, ulong>(tableName, "actor_id");
            Request = new global::SpacetimeDB.Col<DeployableDeployStartEvent, DeployableDeployRequest>(tableName, "request");
        }
    }

    public sealed class DeployableDeployStartEventIxCols
    {

        public DeployableDeployStartEventIxCols(string tableName)
        {
        }
    }
}
