// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EquipmentDescHandle : RemoteTableHandle<EventContext, EquipmentDesc>
        {
            protected override string RemoteTableName => "equipment_desc";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EquipmentDesc row) => row.ItemId;

                public ItemIdUniqueIndex(EquipmentDescHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            public sealed class ShowInProgressionIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(EquipmentDesc row) => row.ShowInProgression;

                public ShowInProgressionIndex(EquipmentDescHandle table) : base(table) { }
            }

            public readonly ShowInProgressionIndex ShowInProgression;

            internal EquipmentDescHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
                ShowInProgression = new(this);
            }

            protected override object GetPrimaryKey(EquipmentDesc row) => row.ItemId;
        }

        public readonly EquipmentDescHandle EquipmentDesc;
    }
}
