// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ExtractEventHandle : RemoteEventTableHandle<EventContext, ExtractEvent>
        {
            public override string RemoteTableName => "extract_event";

            internal ExtractEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ExtractEventHandle ExtractEvent;
    }

    public sealed class ExtractEventCols
    {
        public global::SpacetimeDB.Col<ExtractEvent, ulong> ActorEntityId { get; }
        public global::SpacetimeDB.Col<ExtractEvent, ulong> TargetEntityId { get; }
        public global::SpacetimeDB.Col<ExtractEvent, int> Damage { get; }
        public global::SpacetimeDB.Col<ExtractEvent, bool> IsCrit { get; }

        public ExtractEventCols(string tableName)
        {
            ActorEntityId = new global::SpacetimeDB.Col<ExtractEvent, ulong>(tableName, "actor_entity_id");
            TargetEntityId = new global::SpacetimeDB.Col<ExtractEvent, ulong>(tableName, "target_entity_id");
            Damage = new global::SpacetimeDB.Col<ExtractEvent, int>(tableName, "damage");
            IsCrit = new global::SpacetimeDB.Col<ExtractEvent, bool>(tableName, "is_crit");
        }
    }

    public sealed class ExtractEventIxCols
    {

        public ExtractEventIxCols(string tableName)
        {
        }
    }
}
