// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModThresholdStateHandle : RemoteTableHandle<EventContext, ModThresholdState>
        {
            protected override string RemoteTableName => "mod_threshold_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ModThresholdState row) => row.Id;

                public IdUniqueIndex(ModThresholdStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ThresholdTypeIndex : BTreeIndexBase<byte>
            {
                protected override byte GetKey(ModThresholdState row) => row.ThresholdType;

                public ThresholdTypeIndex(ModThresholdStateHandle table) : base(table) { }
            }

            public readonly ThresholdTypeIndex ThresholdType;

            internal ModThresholdStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ThresholdType = new(this);
            }

            protected override object GetPrimaryKey(ModThresholdState row) => row.Id;
        }

        public readonly ModThresholdStateHandle ModThresholdState;
    }
}
