// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PillarShapingDestroyStartEventHandle : RemoteEventTableHandle<EventContext, PillarShapingDestroyStartEvent>
        {
            public override string RemoteTableName => "pillar_shaping_destroy_start_event";

            internal PillarShapingDestroyStartEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PillarShapingDestroyStartEventHandle PillarShapingDestroyStartEvent;
    }

    public sealed class PillarShapingDestroyStartEventCols
    {
        public global::SpacetimeDB.Col<PillarShapingDestroyStartEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<PillarShapingDestroyStartEvent, PlayerPillarShapingDestroyRequest> Request { get; }

        public PillarShapingDestroyStartEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<PillarShapingDestroyStartEvent, ulong>(tableName, "actor_id");
            Request = new global::SpacetimeDB.Col<PillarShapingDestroyStartEvent, PlayerPillarShapingDestroyRequest>(tableName, "request");
        }
    }

    public sealed class PillarShapingDestroyStartEventIxCols
    {

        public PillarShapingDestroyStartEventIxCols(string tableName)
        {
        }
    }
}
