// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlaceableGrowthTimerHandle : RemoteTableHandle<EventContext, GrowthTimer>
        {
            protected override string RemoteTableName => "placeable_growth_timer";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GrowthTimer row) => row.EntityId;

                public EntityIdUniqueIndex(PlaceableGrowthTimerHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GrowthTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlaceableGrowthTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlaceableGrowthTimerHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GrowthTimer row) => row.ScheduledId;
        }

        public readonly PlaceableGrowthTimerHandle PlaceableGrowthTimer;
    }

    public sealed class PlaceableGrowthTimerCols
    {
        public global::SpacetimeDB.Col<GrowthTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<GrowthTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<GrowthTimer, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<GrowthTimer, int> GrowthRecipeId { get; }

        public PlaceableGrowthTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<GrowthTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<GrowthTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            EntityId = new global::SpacetimeDB.Col<GrowthTimer, ulong>(tableName, "entity_id");
            GrowthRecipeId = new global::SpacetimeDB.Col<GrowthTimer, int>(tableName, "growth_recipe_id");
        }
    }

    public sealed class PlaceableGrowthTimerIxCols
    {
        public global::SpacetimeDB.IxCol<GrowthTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.IxCol<GrowthTimer, ulong> EntityId { get; }

        public PlaceableGrowthTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<GrowthTimer, ulong>(tableName, "scheduled_id");
            EntityId = new global::SpacetimeDB.IxCol<GrowthTimer, ulong>(tableName, "entity_id");
        }
    }
}
