// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingCustomizationStateHandle : RemoteTableHandle<EventContext, PlayerHousingCustomizationState>
        {
            protected override string RemoteTableName => "player_housing_customization_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingCustomizationState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHousingCustomizationStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerHousingCustomizationStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingCustomizationState row) => row.EntityId;
        }

        public readonly PlayerHousingCustomizationStateHandle PlayerHousingCustomizationState;
    }
}
