// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerSignedOutEventHandle : RemoteTableHandle<EventContext, PlayerSignedOutEvent>
        {
            protected override string RemoteTableName => "player_signed_out_event";

            internal PlayerSignedOutEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PlayerSignedOutEventHandle PlayerSignedOutEvent;
    }

    public sealed class PlayerSignedOutEventCols
    {
        public global::SpacetimeDB.Col<PlayerSignedOutEvent, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<PlayerSignedOutEvent, PlayerSignedOutReason> Reason { get; }

        public PlayerSignedOutEventCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<PlayerSignedOutEvent, SpacetimeDB.Identity>(tableName, "identity");
            Reason = new global::SpacetimeDB.Col<PlayerSignedOutEvent, PlayerSignedOutReason>(tableName, "reason");
        }
    }

    public sealed class PlayerSignedOutEventIxCols
    {

        public PlayerSignedOutEventIxCols(string tableName)
        {
        }
    }
}
