// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerSettingsStateV2Handle : RemoteTableHandle<EventContext, PlayerSettingsStateV2>
        {
            protected override string RemoteTableName => "player_settings_state_v2";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerSettingsStateV2 row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerSettingsStateV2Handle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerSettingsStateV2Handle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerSettingsStateV2 row) => row.EntityId;
        }

        public readonly PlayerSettingsStateV2Handle PlayerSettingsStateV2;
    }
}
