// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerDeveloperNotificationStateHandle : RemoteTableHandle<EventContext, PlayerDeveloperNotificationState>
        {
            protected override string RemoteTableName => "player_developer_notification_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerDeveloperNotificationState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerDeveloperNotificationStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerDeveloperNotificationStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerDeveloperNotificationState row) => row.EntityId;
        }

        public readonly PlayerDeveloperNotificationStateHandle PlayerDeveloperNotificationState;
    }
}
