// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerMoveEventHandle : RemoteTableHandle<EventContext, PlayerMoveEvent>
        {
            protected override string RemoteTableName => "player_move_event";

            internal PlayerMoveEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PlayerMoveEventHandle PlayerMoveEvent;
    }

    public sealed class PlayerMoveEventCols
    {
        public global::SpacetimeDB.Col<PlayerMoveEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<PlayerMoveEvent, PlayerMoveRequest> Request { get; }

        public PlayerMoveEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<PlayerMoveEvent, ulong>(tableName, "actor_id");
            Request = new global::SpacetimeDB.Col<PlayerMoveEvent, PlayerMoveRequest>(tableName, "request");
        }
    }

    public sealed class PlayerMoveEventIxCols
    {

        public PlayerMoveEventIxCols(string tableName)
        {
        }
    }
}
