// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProjectSiteAdvanceProjectStartEventHandle : RemoteEventTableHandle<EventContext, ProjectSiteAdvanceProjectStartEvent>
        {
            public override string RemoteTableName => "project_site_advance_project_start_event";

            internal ProjectSiteAdvanceProjectStartEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ProjectSiteAdvanceProjectStartEventHandle ProjectSiteAdvanceProjectStartEvent;
    }

    public sealed class ProjectSiteAdvanceProjectStartEventCols
    {
        public global::SpacetimeDB.Col<ProjectSiteAdvanceProjectStartEvent, ulong> ActorId { get; }
        public global::SpacetimeDB.Col<ProjectSiteAdvanceProjectStartEvent, PlayerProjectSiteAdvanceProjectRequest> Request { get; }

        public ProjectSiteAdvanceProjectStartEventCols(string tableName)
        {
            ActorId = new global::SpacetimeDB.Col<ProjectSiteAdvanceProjectStartEvent, ulong>(tableName, "actor_id");
            Request = new global::SpacetimeDB.Col<ProjectSiteAdvanceProjectStartEvent, PlayerProjectSiteAdvanceProjectRequest>(tableName, "request");
        }
    }

    public sealed class ProjectSiteAdvanceProjectStartEventIxCols
    {

        public ProjectSiteAdvanceProjectStartEventIxCols(string tableName)
        {
        }
    }
}
