// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RegionControlInfoHandle : RemoteTableHandle<EventContext, RegionControlInfo>
        {
            protected override string RemoteTableName => "region_control_info";

            public sealed class RegionIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(RegionControlInfo row) => row.RegionId;

                public RegionIdUniqueIndex(RegionControlInfoHandle table) : base(table) { }
            }

            public readonly RegionIdUniqueIndex RegionId;

            internal RegionControlInfoHandle(DbConnection conn) : base(conn)
            {
                RegionId = new(this);
            }

            protected override object GetPrimaryKey(RegionControlInfo row) => row.RegionId;
        }

        public readonly RegionControlInfoHandle RegionControlInfo;
    }
}
