// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourcePlacementRecipeDescV2Handle : RemoteTableHandle<EventContext, ResourcePlacementRecipeDescV2>
        {
            protected override string RemoteTableName => "resource_placement_recipe_desc_v2";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ResourcePlacementRecipeDescV2 row) => row.Id;

                public IdUniqueIndex(ResourcePlacementRecipeDescV2Handle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ResourcePlacementRecipeDescV2Handle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ResourcePlacementRecipeDescV2 row) => row.Id;
        }

        public readonly ResourcePlacementRecipeDescV2Handle ResourcePlacementRecipeDescV2;
    }
}
