// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedClaimTechDescHandle : RemoteTableHandle<EventContext, ClaimTechDesc>
        {
            protected override string RemoteTableName => "staged_claim_tech_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ClaimTechDesc row) => row.Id;

                public IdUniqueIndex(StagedClaimTechDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedClaimTechDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ClaimTechDesc row) => row.Id;
        }

        public readonly StagedClaimTechDescHandle StagedClaimTechDesc;
    }
}
