// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedCombatActionMultiHitDescHandle : RemoteTableHandle<EventContext, CombatActionMultiHitDesc>
        {
            protected override string RemoteTableName => "staged_combat_action_multi_hit_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CombatActionMultiHitDesc row) => row.Id;

                public IdUniqueIndex(StagedCombatActionMultiHitDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedCombatActionMultiHitDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CombatActionMultiHitDesc row) => row.Id;
        }

        public readonly StagedCombatActionMultiHitDescHandle StagedCombatActionMultiHitDesc;
    }
}
