// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedClaimTileCostHandle : RemoteTableHandle<EventContext, ClaimTileCost>
        {
            protected override string RemoteTableName => "staged_claim_tile_cost";

            public sealed class TileCountUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ClaimTileCost row) => row.TileCount;

                public TileCountUniqueIndex(StagedClaimTileCostHandle table) : base(table) { }
            }

            public readonly TileCountUniqueIndex TileCount;

            internal StagedClaimTileCostHandle(DbConnection conn) : base(conn)
            {
                TileCount = new(this);
            }

            protected override object GetPrimaryKey(ClaimTileCost row) => row.TileCount;
        }

        public readonly StagedClaimTileCostHandle StagedClaimTileCost;
    }
}
