// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedAlertDescHandle : RemoteTableHandle<EventContext, AlertDesc>
        {
            protected override string RemoteTableName => "staged_alert_desc";

            public sealed class AlertTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(AlertDesc row) => row.AlertType;

                public AlertTypeUniqueIndex(StagedAlertDescHandle table) : base(table) { }
            }

            public readonly AlertTypeUniqueIndex AlertType;

            internal StagedAlertDescHandle(DbConnection conn) : base(conn)
            {
                AlertType = new(this);
            }

            protected override object GetPrimaryKey(AlertDesc row) => row.AlertType;
        }

        public readonly StagedAlertDescHandle StagedAlertDesc;
    }
}
