// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedItemConversionRecipeDescHandle : RemoteTableHandle<EventContext, ItemConversionRecipeDesc>
        {
            protected override string RemoteTableName => "staged_item_conversion_recipe_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ItemConversionRecipeDesc row) => row.Id;

                public IdUniqueIndex(StagedItemConversionRecipeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedItemConversionRecipeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ItemConversionRecipeDesc row) => row.Id;
        }

        public readonly StagedItemConversionRecipeDescHandle StagedItemConversionRecipeDesc;
    }
}
