// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StorageLogCleanupLoopTimerHandle : RemoteTableHandle<EventContext, StorageLogCleanupLoopTimer>
        {
            protected override string RemoteTableName => "storage_log_cleanup_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StorageLogCleanupLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(StorageLogCleanupLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal StorageLogCleanupLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(StorageLogCleanupLoopTimer row) => row.ScheduledId;
        }

        public readonly StorageLogCleanupLoopTimerHandle StorageLogCleanupLoopTimer;
    }
}
