// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WindDbgDescHandle : RemoteTableHandle<EventContext, WindDbgDesc>
        {
            protected override string RemoteTableName => "wind_dbg_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WindDbgDesc row) => row.Id;

                public IdUniqueIndex(WindDbgDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WindDbgDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WindDbgDesc row) => row.Id;
        }

        public readonly WindDbgDescHandle WindDbgDesc;
    }
}
