// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WindParamsDescHandle : RemoteTableHandle<EventContext, WindParamsDesc>
        {
            protected override string RemoteTableName => "wind_params_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WindParamsDesc row) => row.Id;

                public IdUniqueIndex(WindParamsDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WindParamsDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WindParamsDesc row) => row.Id;
        }

        public readonly WindParamsDescHandle WindParamsDesc;
    }
}
