// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CheatShardsGrantRequest
    {
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "shards")]
        public uint Shards;

        public CheatShardsGrantRequest(
            ulong OwnerEntityId,
            uint Shards
        )
        {
            this.OwnerEntityId = OwnerEntityId;
            this.Shards = Shards;
        }

        public CheatShardsGrantRequest()
        {
        }
    }
}
