// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireMarkForExpansionRequest
    {
        [DataMember(Name = "empire_entity_id")]
        public ulong EmpireEntityId;
        [DataMember(Name = "chunk_index")]
        public ulong ChunkIndex;
        [DataMember(Name = "enabled")]
        public bool Enabled;

        public EmpireMarkForExpansionRequest(
            ulong EmpireEntityId,
            ulong ChunkIndex,
            bool Enabled
        )
        {
            this.EmpireEntityId = EmpireEntityId;
            this.ChunkIndex = ChunkIndex;
            this.Enabled = Enabled;
        }

        public EmpireMarkForExpansionRequest()
        {
        }
    }
}
