// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerPillarShapingPlaceRequest
    {
        [DataMember(Name = "coordinates")]
        public OffsetCoordinatesLargeMessage Coordinates;
        [DataMember(Name = "pillar_type_id")]
        public int PillarTypeId;

        public PlayerPillarShapingPlaceRequest(
            OffsetCoordinatesLargeMessage Coordinates,
            int PillarTypeId
        )
        {
            this.Coordinates = Coordinates;
            this.PillarTypeId = PillarTypeId;
        }

        public PlayerPillarShapingPlaceRequest()
        {
            this.Coordinates = new();
        }
    }
}
