// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerShardState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "shards")]
        public uint Shards;
        [DataMember(Name = "last_shard_claim")]
        public int LastShardClaim;

        public PlayerShardState(
            ulong EntityId,
            uint Shards,
            int LastShardClaim
        )
        {
            this.EntityId = EntityId;
            this.Shards = Shards;
            this.LastShardClaim = LastShardClaim;
        }

        public PlayerShardState()
        {
        }
    }
}
