// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    public enum EquipmentSlotType
    {
        MainHand,
        OffHand,
        HeadArtifact,
        TorsoArtifact,
        HandArtifact,
        FeetArtifact,
        HeadClothing,
        TorsoClothing,
        HandClothing,
        BeltClothing,
        LegClothing,
        FeetClothing,
        None,
        ForestryCharm,
        ForestryInstrument,
        CarpentryCharm,
        CarpentryInstrument,
        MasonryCharm,
        MasonryInstrument,
        MiningCharm,
        MiningInstrument,
        SmithingCharm,
        SmithingInstrument,
        LeatherworkingCharm,
        LeatherworkingInstrument,
        HuntingCharm,
        HuntingInstrument,
        TailoringCharm,
        TailoringInstrument,
        FarmingCharm,
        FarmingInstrument,
        FishingCharm,
        FishingInstrument,
        ForagingCharm,
        ForagingInstrument,
        ScholarCharm,
        ScholarInstrument,
    }
}
