// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PillarShapingDestroyStartEvent
    {
        [DataMember(Name = "actor_id")]
        public ulong ActorId;
        [DataMember(Name = "request")]
        public PlayerPillarShapingDestroyRequest Request;

        public PillarShapingDestroyStartEvent(
            ulong ActorId,
            PlayerPillarShapingDestroyRequest Request
        )
        {
            this.ActorId = ActorId;
            this.Request = Request;
        }

        public PillarShapingDestroyStartEvent()
        {
            this.Request = new();
        }
    }
}
