// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PremiumItemDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "image_address")]
        public string ImageAddress;
        [DataMember(Name = "collectible_desc_id")]
        public int CollectibleDescId;
        [DataMember(Name = "price")]
        public uint Price;
        [DataMember(Name = "base_price")]
        public uint BasePrice;
        [DataMember(Name = "is_enabled")]
        public bool IsEnabled;
        [DataMember(Name = "quantity")]
        public uint Quantity;

        public PremiumItemDesc(
            int Id,
            string Name,
            string Description,
            string ImageAddress,
            int CollectibleDescId,
            uint Price,
            uint BasePrice,
            bool IsEnabled,
            uint Quantity
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.ImageAddress = ImageAddress;
            this.CollectibleDescId = CollectibleDescId;
            this.Price = Price;
            this.BasePrice = BasePrice;
            this.IsEnabled = IsEnabled;
            this.Quantity = Quantity;
        }

        public PremiumItemDesc()
        {
            this.Name = "";
            this.Description = "";
            this.ImageAddress = "";
        }
    }
}
