// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PremiumPurchaseState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "collectible_desc_id")]
        public int? CollectibleDescId;
        [DataMember(Name = "price")]
        public uint Price;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;
        [DataMember(Name = "processed")]
        public bool Processed;
        [DataMember(Name = "quantity")]
        public uint Quantity;

        public PremiumPurchaseState(
            ulong EntityId,
            SpacetimeDB.Identity Identity,
            int? CollectibleDescId,
            uint Price,
            SpacetimeDB.Timestamp Timestamp,
            bool Processed,
            uint Quantity
        )
        {
            this.EntityId = EntityId;
            this.Identity = Identity;
            this.CollectibleDescId = CollectibleDescId;
            this.Price = Price;
            this.Timestamp = Timestamp;
            this.Processed = Processed;
            this.Quantity = Quantity;
        }

        public PremiumPurchaseState()
        {
        }
    }
}
