// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RegionDestroySiegeEngineMsg
    {
        [DataMember(Name = "deployable_entity_id")]
        public ulong DeployableEntityId;

        public RegionDestroySiegeEngineMsg(ulong DeployableEntityId)
        {
            this.DeployableEntityId = DeployableEntityId;
        }

        public RegionDestroySiegeEngineMsg()
        {
        }
    }
}
