// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SkillLevelKnowledgeDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "skill_id")]
        public int SkillId;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "secondary_knowledge_id")]
        public int SecondaryKnowledgeId;

        public SkillLevelKnowledgeDesc(
            int Id,
            int SkillId,
            int Level,
            int SecondaryKnowledgeId
        )
        {
            this.Id = Id;
            this.SkillId = SkillId;
            this.Level = Level;
            this.SecondaryKnowledgeId = SecondaryKnowledgeId;
        }

        public SkillLevelKnowledgeDesc()
        {
        }
    }
}
