// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminInsertResourceGrowthTimerHandler(ReducerEventContext ctx, int resourceId);
        public event AdminInsertResourceGrowthTimerHandler? OnAdminInsertResourceGrowthTimer;

        public void AdminInsertResourceGrowthTimer(int resourceId)
        {
            conn.InternalCallReducer(new Reducer.AdminInsertResourceGrowthTimer(resourceId), this.SetCallReducerFlags.AdminInsertResourceGrowthTimerFlags);
        }

        public bool InvokeAdminInsertResourceGrowthTimer(ReducerEventContext ctx, Reducer.AdminInsertResourceGrowthTimer args)
        {
            if (OnAdminInsertResourceGrowthTimer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminInsertResourceGrowthTimer(
                ctx,
                args.ResourceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminInsertResourceGrowthTimer : Reducer, IReducerArgs
        {
            [DataMember(Name = "resource_id")]
            public int ResourceId;

            public AdminInsertResourceGrowthTimer(int ResourceId)
            {
                this.ResourceId = ResourceId;
            }

            public AdminInsertResourceGrowthTimer()
            {
            }

            string IReducerArgs.ReducerName => "admin_insert_resource_growth_timer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminInsertResourceGrowthTimerFlags;
        public void AdminInsertResourceGrowthTimer(CallReducerFlags flags) => AdminInsertResourceGrowthTimerFlags = flags;
    }
}
