// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminExpelPlayersHandler(ReducerEventContext ctx, bool commit);
        public event AdminExpelPlayersHandler? OnAdminExpelPlayers;

        public void AdminExpelPlayers(bool commit)
        {
            conn.InternalCallReducer(new Reducer.AdminExpelPlayers(commit), this.SetCallReducerFlags.AdminExpelPlayersFlags);
        }

        public bool InvokeAdminExpelPlayers(ReducerEventContext ctx, Reducer.AdminExpelPlayers args)
        {
            if (OnAdminExpelPlayers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminExpelPlayers(
                ctx,
                args.Commit
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminExpelPlayers : Reducer, IReducerArgs
        {
            [DataMember(Name = "commit")]
            public bool Commit;

            public AdminExpelPlayers(bool Commit)
            {
                this.Commit = Commit;
            }

            public AdminExpelPlayers()
            {
            }

            string IReducerArgs.ReducerName => "admin_expel_players";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminExpelPlayersFlags;
        public void AdminExpelPlayers(CallReducerFlags flags) => AdminExpelPlayersFlags = flags;
    }
}
