// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DirectMessagePostMessageHandler(ReducerEventContext ctx, string receiver, string text);
        public event DirectMessagePostMessageHandler? OnDirectMessagePostMessage;

        public void DirectMessagePostMessage(string receiver, string text)
        {
            conn.InternalCallReducer(new Reducer.DirectMessagePostMessage(receiver, text), this.SetCallReducerFlags.DirectMessagePostMessageFlags);
        }

        public bool InvokeDirectMessagePostMessage(ReducerEventContext ctx, Reducer.DirectMessagePostMessage args)
        {
            if (OnDirectMessagePostMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDirectMessagePostMessage(
                ctx,
                args.Receiver,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DirectMessagePostMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "receiver")]
            public string Receiver;
            [DataMember(Name = "text")]
            public string Text;

            public DirectMessagePostMessage(
                string Receiver,
                string Text
            )
            {
                this.Receiver = Receiver;
                this.Text = Text;
            }

            public DirectMessagePostMessage()
            {
                this.Receiver = "";
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "direct_message_post_message";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DirectMessagePostMessageFlags;
        public void DirectMessagePostMessage(CallReducerFlags flags) => DirectMessagePostMessageFlags = flags;
    }
}
