// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrateLuminateCavesHandler(ReducerEventContext ctx, bool commit);
        public event MigrateLuminateCavesHandler? OnMigrateLuminateCaves;

        public void MigrateLuminateCaves(bool commit)
        {
            conn.InternalCallReducer(new Reducer.MigrateLuminateCaves(commit), this.SetCallReducerFlags.MigrateLuminateCavesFlags);
        }

        public bool InvokeMigrateLuminateCaves(ReducerEventContext ctx, Reducer.MigrateLuminateCaves args)
        {
            if (OnMigrateLuminateCaves == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrateLuminateCaves(
                ctx,
                args.Commit
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrateLuminateCaves : Reducer, IReducerArgs
        {
            [DataMember(Name = "commit")]
            public bool Commit;

            public MigrateLuminateCaves(bool Commit)
            {
                this.Commit = Commit;
            }

            public MigrateLuminateCaves()
            {
            }

            string IReducerArgs.ReducerName => "migrate_luminate_caves";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MigrateLuminateCavesFlags;
        public void MigrateLuminateCaves(CallReducerFlags flags) => MigrateLuminateCavesFlags = flags;
    }
}
