// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageBuildingMapIconDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraftRegion.Types.BuildingMapIconDesc> records);
        public event StageBuildingMapIconDescHandler? OnStageBuildingMapIconDesc;

        public void StageBuildingMapIconDesc(System.Collections.Generic.List<BitCraftRegion.Types.BuildingMapIconDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageBuildingMapIconDesc(records), this.SetCallReducerFlags.StageBuildingMapIconDescFlags);
        }

        public bool InvokeStageBuildingMapIconDesc(ReducerEventContext ctx, Reducer.StageBuildingMapIconDesc args)
        {
            if (OnStageBuildingMapIconDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageBuildingMapIconDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageBuildingMapIconDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<BuildingMapIconDesc> Records;

            public StageBuildingMapIconDesc(System.Collections.Generic.List<BuildingMapIconDesc> Records)
            {
                this.Records = Records;
            }

            public StageBuildingMapIconDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_building_map_icon_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageBuildingMapIconDescFlags;
        public void StageBuildingMapIconDesc(CallReducerFlags flags) => StageBuildingMapIconDescFlags = flags;
    }
}
