// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageCombatActionDescV3Handler(ReducerEventContext ctx, System.Collections.Generic.List<CombatActionDescV3> records);
        public event StageCombatActionDescV3Handler? OnStageCombatActionDescV3;

        public void StageCombatActionDescV3(System.Collections.Generic.List<CombatActionDescV3> records)
        {
            conn.InternalCallReducer(new Reducer.StageCombatActionDescV3(records), this.SetCallReducerFlags.StageCombatActionDescV3Flags);
        }

        public bool InvokeStageCombatActionDescV3(ReducerEventContext ctx, Reducer.StageCombatActionDescV3 args)
        {
            if (OnStageCombatActionDescV3 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageCombatActionDescV3(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageCombatActionDescV3 : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<CombatActionDescV3> Records;

            public StageCombatActionDescV3(System.Collections.Generic.List<CombatActionDescV3> Records)
            {
                this.Records = Records;
            }

            public StageCombatActionDescV3()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_combat_action_desc_v3";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageCombatActionDescV3Flags;
        public void StageCombatActionDescV3(CallReducerFlags flags) => StageCombatActionDescV3Flags = flags;
    }
}
