// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftGlobal.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageBuildingPortalDescV2Handler(ReducerEventContext ctx, System.Collections.Generic.List<BuildingPortalDescV2> records);
        public event StageBuildingPortalDescV2Handler? OnStageBuildingPortalDescV2;

        public void StageBuildingPortalDescV2(System.Collections.Generic.List<BuildingPortalDescV2> records)
        {
            conn.InternalCallReducer(new Reducer.StageBuildingPortalDescV2(records), this.SetCallReducerFlags.StageBuildingPortalDescV2Flags);
        }

        public bool InvokeStageBuildingPortalDescV2(ReducerEventContext ctx, Reducer.StageBuildingPortalDescV2 args)
        {
            if (OnStageBuildingPortalDescV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageBuildingPortalDescV2(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageBuildingPortalDescV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<BuildingPortalDescV2> Records;

            public StageBuildingPortalDescV2(System.Collections.Generic.List<BuildingPortalDescV2> Records)
            {
                this.Records = Records;
            }

            public StageBuildingPortalDescV2()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_building_portal_desc_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageBuildingPortalDescV2Flags;
        public void StageBuildingPortalDescV2(CallReducerFlags flags) => StageBuildingPortalDescV2Flags = flags;
    }
}
