// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireFoundryStateHandle : RemoteTableHandle<EventContext, EmpireFoundryState>
        {
            protected override string RemoteTableName => "empire_foundry_state";

            public sealed class EmpireEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireFoundryState row) => row.EmpireEntityId;

                public EmpireEntityIdIndex(EmpireFoundryStateHandle table) : base(table) { }
            }

            public readonly EmpireEntityIdIndex EmpireEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireFoundryState row) => row.EntityId;

                public EntityIdUniqueIndex(EmpireFoundryStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EmpireFoundryStateHandle(DbConnection conn) : base(conn)
            {
                EmpireEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EmpireFoundryState row) => row.EntityId;
        }

        public readonly EmpireFoundryStateHandle EmpireFoundryState;
    }
}
