// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireCraftSuppliesTimerHandle : RemoteTableHandle<EventContext, EmpireCraftSuppliesTimer>
        {
            protected override string RemoteTableName => "empire_craft_supplies_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireCraftSuppliesTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EmpireCraftSuppliesTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EmpireCraftSuppliesTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EmpireCraftSuppliesTimer row) => row.ScheduledId;
        }

        public readonly EmpireCraftSuppliesTimerHandle EmpireCraftSuppliesTimer;
    }
}
