// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type AchievementDesc = {
  id: number,
  name: string,
  description: string,
  requisites: number[],
  skillId: number,
  skillLevel: number,
  resourceDisc: number[],
  craftingDisc: number[],
  cargoDisc: number[],
  itemDisc: number[],
  collectibleRewards: number[],
  pointsReward: number,
  pctChunksDiscovered: number,
  chunksDiscovered: number,
};
/**
 * An object for generated helper functions.
 */
export const AchievementDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "description", algebraicType: __AlgebraicTypeValue.String},
        { name: "requisites", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "skillId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "skillLevel", algebraicType: __AlgebraicTypeValue.I32},
        { name: "resourceDisc", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "craftingDisc", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "cargoDisc", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "itemDisc", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "collectibleRewards", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "pointsReward", algebraicType: __AlgebraicTypeValue.I32},
        { name: "pctChunksDiscovered", algebraicType: __AlgebraicTypeValue.F32},
        { name: "chunksDiscovered", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AchievementDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, AchievementDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AchievementDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, AchievementDesc.getTypeScriptAlgebraicType());
  },

}

export default AchievementDesc;


