// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ActiveEnvironmentBuffState } from "./active_environment_buff_state_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `active_environment_buff_state`.
 *
 * Obtain a handle from the [`activeEnvironmentBuffState`] property on [`RemoteTables`],
 * like `ctx.db.activeEnvironmentBuffState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.activeEnvironmentBuffState.on_insert(...)`.
 */
export class ActiveEnvironmentBuffStateTableHandle {
  tableCache: TableCache<ActiveEnvironmentBuffState>;

  constructor(tableCache: TableCache<ActiveEnvironmentBuffState>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ActiveEnvironmentBuffState> {
    return this.tableCache.iter();
  }

  onInsert = (cb: (ctx: EventContext, row: ActiveEnvironmentBuffState) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ActiveEnvironmentBuffState) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ActiveEnvironmentBuffState) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ActiveEnvironmentBuffState) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
