// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ActionLogSubjectType } from "./action_log_subject_type_type";
// Mark import as potentially unused
declare type __keep_ActionLogSubjectType = ActionLogSubjectType;
import { ActionLogData } from "./action_log_data_type";
// Mark import as potentially unused
declare type __keep_ActionLogData = ActionLogData;


export type ActionLogState = {
  id: bigint,
  objectEntityId: bigint,
  subjectEntityId: bigint,
  subjectName: string,
  subjectType: ActionLogSubjectType,
  data: ActionLogData,
  timestamp: __Timestamp,
  daysSinceEpoch: number,
};
/**
 * An object for generated helper functions.
 */
export const ActionLogState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U64},
        { name: "objectEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "subjectEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "subjectName", algebraicType: __AlgebraicTypeValue.String},
        { name: "subjectType", algebraicType: ActionLogSubjectType.getTypeScriptAlgebraicType()},
        { name: "data", algebraicType: ActionLogData.getTypeScriptAlgebraicType()},
        { name: "timestamp", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "daysSinceEpoch", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ActionLogState): void {
    __AlgebraicTypeValue.serializeValue(writer, ActionLogState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ActionLogState {
    return __AlgebraicTypeValue.deserializeValue(reader, ActionLogState.getTypeScriptAlgebraicType());
  },

}

export default ActionLogState;


