// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ActionLogSubjectType as __ActionLogSubjectType } from "./action_log_subject_type_type";
import { ActionLogData as __ActionLogData } from "./action_log_data_type";

export type ActionLogState = {
  id: bigint,
  objectEntityId: bigint,
  subjectEntityId: bigint,
  subjectName: string,
  subjectType: __ActionLogSubjectType,
  data: __ActionLogData,
  timestamp: Timestamp,
  daysSinceEpoch: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ActionLogState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU64Type()),
      new ProductTypeElement("objectEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("subjectEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("subjectName", AlgebraicType.createStringType()),
      new ProductTypeElement("subjectType", __ActionLogSubjectType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("data", __ActionLogData.getTypeScriptAlgebraicType()),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
      new ProductTypeElement("daysSinceEpoch", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ActionLogState): void {
    ActionLogState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ActionLogState {
    return ActionLogState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


