// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ItemStack } from "./item_stack_type";
// Mark import as potentially unused
declare type __keep_ItemStack = ItemStack;


export type ActionLogDataSpaceAllocator = {
  item1: ItemStack,
  item2: ItemStack,
  val1: bigint,
  val2: bigint,
};
/**
 * An object for generated helper functions.
 */
export const ActionLogDataSpaceAllocator = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "item1", algebraicType: ItemStack.getTypeScriptAlgebraicType()},
        { name: "item2", algebraicType: ItemStack.getTypeScriptAlgebraicType()},
        { name: "val1", algebraicType: __AlgebraicTypeValue.U64},
        { name: "val2", algebraicType: __AlgebraicTypeValue.U64},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ActionLogDataSpaceAllocator): void {
    __AlgebraicTypeValue.serializeValue(writer, ActionLogDataSpaceAllocator.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ActionLogDataSpaceAllocator {
    return __AlgebraicTypeValue.deserializeValue(reader, ActionLogDataSpaceAllocator.getTypeScriptAlgebraicType());
  },

}

export default ActionLogDataSpaceAllocator;


