// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ItemStack } from "./item_stack_type";
// Mark import as potentially unused
declare type __keep_ItemStack = ItemStack;
import { ActionLogDataSpaceAllocator } from "./action_log_data_space_allocator_type";
// Mark import as potentially unused
declare type __keep_ActionLogDataSpaceAllocator = ActionLogDataSpaceAllocator;

import * as ActionLogDataVariants from './action_log_data_variants'

// The tagged union or sum type for the algebraic type `ActionLogData`.
export type ActionLogData = ActionLogDataVariants.Reserved |
  ActionLogDataVariants.WithdrawItem |
  ActionLogDataVariants.DepositItem;

// A value with helper functions to construct the type.
export const ActionLogData = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Reserved: (value: ActionLogDataSpaceAllocator): ActionLogData => ({ tag: "Reserved", value }),
  WithdrawItem: (value: ItemStack): ActionLogData => ({ tag: "WithdrawItem", value }),
  DepositItem: (value: ItemStack): ActionLogData => ({ tag: "DepositItem", value }),

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Reserved", algebraicType: ActionLogDataSpaceAllocator.getTypeScriptAlgebraicType() },
        { name: "WithdrawItem", algebraicType: ItemStack.getTypeScriptAlgebraicType() },
        { name: "DepositItem", algebraicType: ItemStack.getTypeScriptAlgebraicType() },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ActionLogData): void {
      __AlgebraicTypeValue.serializeValue(writer, ActionLogData.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ActionLogData {
      return __AlgebraicTypeValue.deserializeValue(reader, ActionLogData.getTypeScriptAlgebraicType());
  },

}

export default ActionLogData;


