// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type AdminLogModerationAction = {
  reportEntityId: bigint,
  reportedPlayerEntityId: bigint,
  adminName: string,
  reportedPlayerUsername: string,
  actionType: string,
  moderationNotice: string,
  details: string,
};
/**
 * An object for generated helper functions.
 */
export const AdminLogModerationAction = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "reportEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "reportedPlayerEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "adminName", algebraicType: __AlgebraicTypeValue.String},
        { name: "reportedPlayerUsername", algebraicType: __AlgebraicTypeValue.String},
        { name: "actionType", algebraicType: __AlgebraicTypeValue.String},
        { name: "moderationNotice", algebraicType: __AlgebraicTypeValue.String},
        { name: "details", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AdminLogModerationAction): void {
    __AlgebraicTypeValue.serializeValue(writer, AdminLogModerationAction.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AdminLogModerationAction {
    return __AlgebraicTypeValue.deserializeValue(reader, AdminLogModerationAction.getTypeScriptAlgebraicType());
  },

}

export default AdminLogModerationAction;

