// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as BuildingCategoryVariants from './building_category_variants'

// The tagged union or sum type for the algebraic type `BuildingCategory`.
export type BuildingCategory = BuildingCategoryVariants.Storage |
  BuildingCategoryVariants.Crafting |
  BuildingCategoryVariants.Residential |
  BuildingCategoryVariants.TownHall |
  BuildingCategoryVariants.Wall |
  BuildingCategoryVariants.TradingPost |
  BuildingCategoryVariants.Ornamental |
  BuildingCategoryVariants.AncientRuins |
  BuildingCategoryVariants.ClaimTotem |
  BuildingCategoryVariants.TerrraformingBase |
  BuildingCategoryVariants.Barter |
  BuildingCategoryVariants.Portal |
  BuildingCategoryVariants.RentTerminal |
  BuildingCategoryVariants.Watchtower |
  BuildingCategoryVariants.EmpireFoundry |
  BuildingCategoryVariants.Sign |
  BuildingCategoryVariants.Gate |
  BuildingCategoryVariants.Bed |
  BuildingCategoryVariants.Waystone |
  BuildingCategoryVariants.Bank |
  BuildingCategoryVariants.Elevator |
  BuildingCategoryVariants.TownMarket |
  BuildingCategoryVariants.RecoveryChest |
  BuildingCategoryVariants.PlayerHousing;

// A value with helper functions to construct the type.
export const BuildingCategory = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Storage: { tag: "Storage" } as const,
  Crafting: { tag: "Crafting" } as const,
  Residential: { tag: "Residential" } as const,
  TownHall: { tag: "TownHall" } as const,
  Wall: { tag: "Wall" } as const,
  TradingPost: { tag: "TradingPost" } as const,
  Ornamental: { tag: "Ornamental" } as const,
  AncientRuins: { tag: "AncientRuins" } as const,
  ClaimTotem: { tag: "ClaimTotem" } as const,
  TerrraformingBase: { tag: "TerrraformingBase" } as const,
  Barter: { tag: "Barter" } as const,
  Portal: { tag: "Portal" } as const,
  RentTerminal: { tag: "RentTerminal" } as const,
  Watchtower: { tag: "Watchtower" } as const,
  EmpireFoundry: { tag: "EmpireFoundry" } as const,
  Sign: { tag: "Sign" } as const,
  Gate: { tag: "Gate" } as const,
  Bed: { tag: "Bed" } as const,
  Waystone: { tag: "Waystone" } as const,
  Bank: { tag: "Bank" } as const,
  Elevator: { tag: "Elevator" } as const,
  TownMarket: { tag: "TownMarket" } as const,
  RecoveryChest: { tag: "RecoveryChest" } as const,
  PlayerHousing: { tag: "PlayerHousing" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Storage", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Crafting", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Residential", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "TownHall", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Wall", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "TradingPost", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Ornamental", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "AncientRuins", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ClaimTotem", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "TerrraformingBase", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Barter", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Portal", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "RentTerminal", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Watchtower", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "EmpireFoundry", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Sign", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Gate", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Bed", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Waystone", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Bank", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Elevator", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "TownMarket", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "RecoveryChest", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PlayerHousing", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: BuildingCategory): void {
      __AlgebraicTypeValue.serializeValue(writer, BuildingCategory.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): BuildingCategory {
      return __AlgebraicTypeValue.deserializeValue(reader, BuildingCategory.getTypeScriptAlgebraicType());
  },

}

export default BuildingCategory;


