// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as ClaimTypeVariants from './claim_type_variants'

// The tagged union or sum type for the algebraic type `ClaimType`.
export type ClaimType = ClaimTypeVariants.Source |
  ClaimTypeVariants.Extension |
  ClaimTypeVariants.Neutral;

// A value with helper functions to construct the type.
export const ClaimType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Source: { tag: "Source" } as const,
  Extension: { tag: "Extension" } as const,
  Neutral: { tag: "Neutral" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Source", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Extension", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Neutral", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ClaimType): void {
      __AlgebraicTypeValue.serializeValue(writer, ClaimType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ClaimType {
      return __AlgebraicTypeValue.deserializeValue(reader, ClaimType.getTypeScriptAlgebraicType());
  },

}

export default ClaimType;


