// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type ClaimTechState = {
  entityId: bigint,
  learned: number[],
  researching: number,
  startTimestamp: __Timestamp,
  scheduledId: bigint | undefined,
};
/**
 * An object for generated helper functions.
 */
export const ClaimTechState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "learned", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "researching", algebraicType: __AlgebraicTypeValue.I32},
        { name: "startTimestamp", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "scheduledId", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U64)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ClaimTechState): void {
    __AlgebraicTypeValue.serializeValue(writer, ClaimTechState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ClaimTechState {
    return __AlgebraicTypeValue.deserializeValue(reader, ClaimTechState.getTypeScriptAlgebraicType());
  },

}

export default ClaimTechState;


