// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as ClothingMaskVariants from './clothing_mask_variants'

// The tagged union or sum type for the algebraic type `ClothingMask`.
export type ClothingMask = ClothingMaskVariants.None |
  ClothingMaskVariants.HairFront |
  ClothingMaskVariants.HairBottom |
  ClothingMaskVariants.HairFull;

// A value with helper functions to construct the type.
export const ClothingMask = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  None: { tag: "None" } as const,
  HairFront: { tag: "HairFront" } as const,
  HairBottom: { tag: "HairBottom" } as const,
  HairFull: { tag: "HairFull" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "None", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "HairFront", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "HairBottom", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "HairFull", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ClothingMask): void {
      __AlgebraicTypeValue.serializeValue(writer, ClothingMask.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ClothingMask {
      return __AlgebraicTypeValue.deserializeValue(reader, ClothingMask.getTypeScriptAlgebraicType());
  },

}

export default ClothingMask;


