// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteTranslationCorrectionArgs {
    pub id: u64,
}

impl From<DeleteTranslationCorrectionArgs> for super::Reducer {
    fn from(args: DeleteTranslationCorrectionArgs) -> Self {
        Self::DeleteTranslationCorrection { id: args.id }
    }
}

impl __sdk::InModule for DeleteTranslationCorrectionArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteTranslationCorrectionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_translation_correction`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_translation_correction {
    /// Request that the remote module invoke the reducer `delete_translation_correction` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_translation_correction`] callbacks.
    fn delete_translation_correction(&self, id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_translation_correction`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteTranslationCorrectionCallbackId`] can be passed to [`Self::remove_on_delete_translation_correction`]
    /// to cancel the callback.
    fn on_delete_translation_correction(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteTranslationCorrectionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_translation_correction`],
    /// causing it not to run in the future.
    fn remove_on_delete_translation_correction(
        &self,
        callback: DeleteTranslationCorrectionCallbackId,
    );
}

impl delete_translation_correction for super::RemoteReducers {
    fn delete_translation_correction(&self, id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "delete_translation_correction",
            DeleteTranslationCorrectionArgs { id },
        )
    }
    fn on_delete_translation_correction(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> DeleteTranslationCorrectionCallbackId {
        DeleteTranslationCorrectionCallbackId(self.imp.on_reducer(
            "delete_translation_correction",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteTranslationCorrection { id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id)
            }),
        ))
    }
    fn remove_on_delete_translation_correction(
        &self,
        callback: DeleteTranslationCorrectionCallbackId,
    ) {
        self.imp
            .remove_on_reducer("delete_translation_correction", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_translation_correction`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_translation_correction {
    /// Set the call-reducer flags for the reducer `delete_translation_correction` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_translation_correction(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_translation_correction for super::SetReducerFlags {
    fn delete_translation_correction(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("delete_translation_correction", flags);
    }
}
