// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { DeployableCollectibleState } from "./deployable_collectible_state_type";
import { OffsetCoordinatesSmallMessage } from "./offset_coordinates_small_message_type";
// Mark import as potentially unused
declare type __keep_OffsetCoordinatesSmallMessage = OffsetCoordinatesSmallMessage;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `deployable_collectible_state`.
 *
 * Obtain a handle from the [`deployableCollectibleState`] property on [`RemoteTables`],
 * like `ctx.db.deployableCollectibleState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.deployableCollectibleState.on_insert(...)`.
 */
export class DeployableCollectibleStateTableHandle {
  tableCache: __TableCache<DeployableCollectibleState>;

  constructor(tableCache: __TableCache<DeployableCollectibleState>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DeployableCollectibleState> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `deployableEntityId` unique index on the table `deployable_collectible_state`,
   * which allows point queries on the field of the same name
   * via the [`DeployableCollectibleStateDeployableEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.deployableCollectibleState.deployableEntityId().find(...)`.
   *
   * Get a handle on the `deployableEntityId` unique index on the table `deployable_collectible_state`.
   */
  deployableEntityId = {
    // Find the subscribed row whose `deployableEntityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): DeployableCollectibleState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.deployableEntityId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DeployableCollectibleState) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DeployableCollectibleState) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DeployableCollectibleState) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DeployableCollectibleState) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DeployableCollectibleState, newRow: DeployableCollectibleState) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DeployableCollectibleState, newRow: DeployableCollectibleState) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
