// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { OffsetCoordinatesSmallMessage } from "./offset_coordinates_small_message_type";
// Mark import as potentially unused
declare type __keep_OffsetCoordinatesSmallMessage = OffsetCoordinatesSmallMessage;


export type DeployableCollectibleStateV2 = {
  deployableEntityId: bigint,
  ownerEntityId: bigint,
  collectibleId: number,
  deployableDescId: number,
  location: OffsetCoordinatesSmallMessage | undefined,
  autoFollow: boolean,
};
/**
 * An object for generated helper functions.
 */
export const DeployableCollectibleStateV2 = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "deployableEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "ownerEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "collectibleId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "deployableDescId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "location", algebraicType: __AlgebraicTypeValue.createOptionType(OffsetCoordinatesSmallMessage.getTypeScriptAlgebraicType())},
        { name: "autoFollow", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: DeployableCollectibleStateV2): void {
    __AlgebraicTypeValue.serializeValue(writer, DeployableCollectibleStateV2.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): DeployableCollectibleStateV2 {
    return __AlgebraicTypeValue.deserializeValue(reader, DeployableCollectibleStateV2.getTypeScriptAlgebraicType());
  },

}

export default DeployableCollectibleStateV2;


