// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type DeployableAppearanceOverrideDesc = {
  id: number,
  collectibleId: number,
  affectedModelAddress: string,
  modelAddress: string,
  iconAssetName: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace DeployableAppearanceOverrideDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("collectibleId", AlgebraicType.createI32Type()),
      new ProductTypeElement("affectedModelAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("modelAddress", AlgebraicType.createStringType()),
      new ProductTypeElement("iconAssetName", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DeployableAppearanceOverrideDesc): void {
    DeployableAppearanceOverrideDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DeployableAppearanceOverrideDesc {
    return DeployableAppearanceOverrideDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


