// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type EmpireDonateItemMsg = {
  playerEntityId: bigint,
  itemId: number,
  isCargo: boolean,
  count: number,
  onBehalfUsername: string | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireDonateItemMsg {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("playerEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("itemId", AlgebraicType.createI32Type()),
      new ProductTypeElement("isCargo", AlgebraicType.createBoolType()),
      new ProductTypeElement("count", AlgebraicType.createU32Type()),
      new ProductTypeElement("onBehalfUsername", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EmpireDonateItemMsg): void {
    EmpireDonateItemMsg.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EmpireDonateItemMsg {
    return EmpireDonateItemMsg.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


