// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { OffsetCoordinatesSmallMessage } from "./offset_coordinates_small_message_type";
// Mark import as potentially unused
declare type __keep_OffsetCoordinatesSmallMessage = OffsetCoordinatesSmallMessage;


export type EmpireSettlementState = {
  buildingEntityId: bigint,
  claimEntityId: bigint,
  empireEntityId: bigint,
  chunkIndex: bigint,
  canHouseEmpireStorehouse: boolean,
  membersDonations: number,
  location: OffsetCoordinatesSmallMessage,
};
/**
 * An object for generated helper functions.
 */
export const EmpireSettlementState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "buildingEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "claimEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "empireEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "chunkIndex", algebraicType: __AlgebraicTypeValue.U64},
        { name: "canHouseEmpireStorehouse", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "membersDonations", algebraicType: __AlgebraicTypeValue.U32},
        { name: "location", algebraicType: OffsetCoordinatesSmallMessage.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: EmpireSettlementState): void {
    __AlgebraicTypeValue.serializeValue(writer, EmpireSettlementState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): EmpireSettlementState {
    return __AlgebraicTypeValue.deserializeValue(reader, EmpireSettlementState.getTypeScriptAlgebraicType());
  },

}

export default EmpireSettlementState;


