// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type EnemyScalingDesc = {
  id: number,
  enemyTypeId: number,
  requiredPlayersCount: number,
  scaledArmorBonus: number,
  strengthBonus: number,
  accuracyBonus: number,
  evasionBonus: number,
  minDamageBonus: number,
  maxDamageBonus: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EnemyScalingDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("enemyTypeId", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredPlayersCount", AlgebraicType.createI32Type()),
      new ProductTypeElement("scaledArmorBonus", AlgebraicType.createI32Type()),
      new ProductTypeElement("strengthBonus", AlgebraicType.createI32Type()),
      new ProductTypeElement("accuracyBonus", AlgebraicType.createI32Type()),
      new ProductTypeElement("evasionBonus", AlgebraicType.createI32Type()),
      new ProductTypeElement("minDamageBonus", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxDamageBonus", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EnemyScalingDesc): void {
    EnemyScalingDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EnemyScalingDesc {
    return EnemyScalingDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


