// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { EnemyType } from "./enemy_type_type";
// Mark import as potentially unused
declare type __keep_EnemyType = EnemyType;
import { Biome } from "./biome_type";
// Mark import as potentially unused
declare type __keep_Biome = Biome;


export type EnemyAiParamsDesc = {
  id: number,
  enemyType: EnemyType,
  biome: Biome,
  avgHerdSize: number,
  varHerdSize: number,
  herdsPerChunk: number,
  roamingDistance: number,
  spawnEagerness: number,
  timeOfDayStart: number,
  timeOfDayEnd: number,
  spawnFrequencyMinutes: number,
};
/**
 * An object for generated helper functions.
 */
export const EnemyAiParamsDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "enemyType", algebraicType: EnemyType.getTypeScriptAlgebraicType()},
        { name: "biome", algebraicType: Biome.getTypeScriptAlgebraicType()},
        { name: "avgHerdSize", algebraicType: __AlgebraicTypeValue.I32},
        { name: "varHerdSize", algebraicType: __AlgebraicTypeValue.F32},
        { name: "herdsPerChunk", algebraicType: __AlgebraicTypeValue.F32},
        { name: "roamingDistance", algebraicType: __AlgebraicTypeValue.I32},
        { name: "spawnEagerness", algebraicType: __AlgebraicTypeValue.F32},
        { name: "timeOfDayStart", algebraicType: __AlgebraicTypeValue.F32},
        { name: "timeOfDayEnd", algebraicType: __AlgebraicTypeValue.F32},
        { name: "spawnFrequencyMinutes", algebraicType: __AlgebraicTypeValue.F32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: EnemyAiParamsDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, EnemyAiParamsDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): EnemyAiParamsDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, EnemyAiParamsDesc.getTypeScriptAlgebraicType());
  },

}

export default EnemyAiParamsDesc;


