// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { LevelRequirement } from "./level_requirement_type";
// Mark import as potentially unused
declare type __keep_LevelRequirement = LevelRequirement;
import { ToolRequirement } from "./tool_requirement_type";
// Mark import as potentially unused
declare type __keep_ToolRequirement = ToolRequirement;
import { InputItemStack } from "./input_item_stack_type";
// Mark import as potentially unused
declare type __keep_InputItemStack = InputItemStack;
import { ExperienceStackF32 } from "./experience_stack_f_32_type";
// Mark import as potentially unused
declare type __keep_ExperienceStackF32 = ExperienceStackF32;
import { ProbabilisticItemStack } from "./probabilistic_item_stack_type";
// Mark import as potentially unused
declare type __keep_ProbabilisticItemStack = ProbabilisticItemStack;


export type ExtractionRecipeDesc = {
  id: number,
  resourceId: number,
  cargoId: number,
  discoveryTriggers: number[],
  requiredKnowledges: number[],
  timeRequirement: number,
  staminaRequirement: number,
  toolDurabilityLost: number,
  extractedItemStacks: ProbabilisticItemStack[],
  consumedItemStacks: InputItemStack[],
  range: number,
  toolRequirements: ToolRequirement[],
  allowUseHands: boolean,
  levelRequirements: LevelRequirement[],
  experiencePerProgress: ExperienceStackF32[],
  verbPhrase: string,
  toolMeshIndex: number,
  recipePerformanceId: number,
};
/**
 * An object for generated helper functions.
 */
export const ExtractionRecipeDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "resourceId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "cargoId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "discoveryTriggers", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "requiredKnowledges", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "timeRequirement", algebraicType: __AlgebraicTypeValue.F32},
        { name: "staminaRequirement", algebraicType: __AlgebraicTypeValue.F32},
        { name: "toolDurabilityLost", algebraicType: __AlgebraicTypeValue.I32},
        { name: "extractedItemStacks", algebraicType: __AlgebraicTypeValue.Array(ProbabilisticItemStack.getTypeScriptAlgebraicType())},
        { name: "consumedItemStacks", algebraicType: __AlgebraicTypeValue.Array(InputItemStack.getTypeScriptAlgebraicType())},
        { name: "range", algebraicType: __AlgebraicTypeValue.I32},
        { name: "toolRequirements", algebraicType: __AlgebraicTypeValue.Array(ToolRequirement.getTypeScriptAlgebraicType())},
        { name: "allowUseHands", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "levelRequirements", algebraicType: __AlgebraicTypeValue.Array(LevelRequirement.getTypeScriptAlgebraicType())},
        { name: "experiencePerProgress", algebraicType: __AlgebraicTypeValue.Array(ExperienceStackF32.getTypeScriptAlgebraicType())},
        { name: "verbPhrase", algebraicType: __AlgebraicTypeValue.String},
        { name: "toolMeshIndex", algebraicType: __AlgebraicTypeValue.I32},
        { name: "recipePerformanceId", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ExtractionRecipeDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, ExtractionRecipeDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ExtractionRecipeDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, ExtractionRecipeDesc.getTypeScriptAlgebraicType());
  },

}

export default ExtractionRecipeDesc;


