// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as HexDirectionVariants from './hex_direction_variants'

// The tagged union or sum type for the algebraic type `HexDirection`.
export type HexDirection = HexDirectionVariants.Ne |
  HexDirectionVariants.Ene |
  HexDirectionVariants.E |
  HexDirectionVariants.Ese |
  HexDirectionVariants.Se |
  HexDirectionVariants.S |
  HexDirectionVariants.Sw |
  HexDirectionVariants.Wsw |
  HexDirectionVariants.W |
  HexDirectionVariants.Wnw |
  HexDirectionVariants.Nw |
  HexDirectionVariants.N;

// A value with helper functions to construct the type.
export const HexDirection = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  NE: { tag: "NE" } as const,
  ENE: { tag: "ENE" } as const,
  E: { tag: "E" } as const,
  ESE: { tag: "ESE" } as const,
  SE: { tag: "SE" } as const,
  S: { tag: "S" } as const,
  SW: { tag: "SW" } as const,
  WSW: { tag: "WSW" } as const,
  W: { tag: "W" } as const,
  WNW: { tag: "WNW" } as const,
  NW: { tag: "NW" } as const,
  N: { tag: "N" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "NE", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ENE", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "E", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ESE", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SE", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "S", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SW", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "WSW", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "W", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "WNW", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "NW", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "N", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: HexDirection): void {
      __AlgebraicTypeValue.serializeValue(writer, HexDirection.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): HexDirection {
      return __AlgebraicTypeValue.deserializeValue(reader, HexDirection.getTypeScriptAlgebraicType());
  },

}

export default HexDirection;


