// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ItemStack } from "./item_stack_type";
// Mark import as potentially unused
declare type __keep_ItemStack = ItemStack;


export type ItemConversionRecipeDesc = {
  id: number,
  name: string,
  timeCost: number,
  staminaCost: number,
  locationContext: number,
  stringContext: string,
  outputItem: ItemStack | undefined,
  inputItems: ItemStack[],
  requiredEquipmentId: number,
  requiredEquipmentTier: number,
  allowUseHands: boolean,
  recipePerformanceId: number,
};
/**
 * An object for generated helper functions.
 */
export const ItemConversionRecipeDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "timeCost", algebraicType: __AlgebraicTypeValue.U32},
        { name: "staminaCost", algebraicType: __AlgebraicTypeValue.U32},
        { name: "locationContext", algebraicType: __AlgebraicTypeValue.I32},
        { name: "stringContext", algebraicType: __AlgebraicTypeValue.String},
        { name: "outputItem", algebraicType: __AlgebraicTypeValue.createOptionType(ItemStack.getTypeScriptAlgebraicType())},
        { name: "inputItems", algebraicType: __AlgebraicTypeValue.Array(ItemStack.getTypeScriptAlgebraicType())},
        { name: "requiredEquipmentId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "requiredEquipmentTier", algebraicType: __AlgebraicTypeValue.I32},
        { name: "allowUseHands", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "recipePerformanceId", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ItemConversionRecipeDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, ItemConversionRecipeDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ItemConversionRecipeDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, ItemConversionRecipeDesc.getTypeScriptAlgebraicType());
  },

}

export default ItemConversionRecipeDesc;


