// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as KnowledgeStateVariants from './knowledge_state_variants'

// The tagged union or sum type for the algebraic type `KnowledgeState`.
export type KnowledgeState = KnowledgeStateVariants.Unknown |
  KnowledgeStateVariants.Discovered |
  KnowledgeStateVariants.Acquired;

// A value with helper functions to construct the type.
export const KnowledgeState = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Unknown: { tag: "Unknown" } as const,
  Discovered: { tag: "Discovered" } as const,
  Acquired: { tag: "Acquired" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Unknown", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Discovered", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Acquired", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: KnowledgeState): void {
      __AlgebraicTypeValue.serializeValue(writer, KnowledgeState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): KnowledgeState {
      return __AlgebraicTypeValue.deserializeValue(reader, KnowledgeState.getTypeScriptAlgebraicType());
  },

}

export default KnowledgeState;


