// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ItemType as __ItemType } from "./item_type_type";
import { MarketOrderType as __MarketOrderType } from "./market_order_type_type";

export type MarketTradeEvent = {
  claimEntityId: bigint,
  listingEntityId: bigint,
  listingType: __MarketOrderType,
  buyerEntityId: bigint,
  sellerEntityId: bigint,
  itemId: number,
  itemType: __ItemType,
  quantity: number,
  unitPrice: number,
  listingRemainingQuantity: number,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace MarketTradeEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("claimEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("listingEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("listingType", __MarketOrderType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("buyerEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("sellerEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("itemId", AlgebraicType.createI32Type()),
      new ProductTypeElement("itemType", __ItemType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("quantity", AlgebraicType.createI32Type()),
      new ProductTypeElement("unitPrice", AlgebraicType.createI32Type()),
      new ProductTypeElement("listingRemainingQuantity", AlgebraicType.createI32Type()),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: MarketTradeEvent): void {
    MarketTradeEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): MarketTradeEvent {
    return MarketTradeEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


