// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { InterModuleTableUpdates } from "./inter_module_table_updates_type";
// Mark import as potentially unused
declare type __keep_InterModuleTableUpdates = InterModuleTableUpdates;
import { TransferPlayerMsg } from "./transfer_player_msg_type";
// Mark import as potentially unused
declare type __keep_TransferPlayerMsg = TransferPlayerMsg;
import { TransferPlayerHousingMsg } from "./transfer_player_housing_msg_type";
// Mark import as potentially unused
declare type __keep_TransferPlayerHousingMsg = TransferPlayerHousingMsg;
import { PlayerCreateMsg } from "./player_create_msg_type";
// Mark import as potentially unused
declare type __keep_PlayerCreateMsg = PlayerCreateMsg;
import { UserUpdateRegionMsg } from "./user_update_region_msg_type";
// Mark import as potentially unused
declare type __keep_UserUpdateRegionMsg = UserUpdateRegionMsg;
import { OnPlayerNameSetMsg } from "./on_player_name_set_msg_type";
// Mark import as potentially unused
declare type __keep_OnPlayerNameSetMsg = OnPlayerNameSetMsg;
import { ClaimCreateEmpireSettlementMsg } from "./claim_create_empire_settlement_msg_type";
// Mark import as potentially unused
declare type __keep_ClaimCreateEmpireSettlementMsg = ClaimCreateEmpireSettlementMsg;
import { OnClaimMembersChangedMsg } from "./on_claim_members_changed_msg_type";
// Mark import as potentially unused
declare type __keep_OnClaimMembersChangedMsg = OnClaimMembersChangedMsg;
import { EmpireCreateBuildingMsg } from "./empire_create_building_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireCreateBuildingMsg = EmpireCreateBuildingMsg;
import { OnEmpireBuildingDeletedMsg } from "./on_empire_building_deleted_msg_type";
// Mark import as potentially unused
declare type __keep_OnEmpireBuildingDeletedMsg = OnEmpireBuildingDeletedMsg;
import { GlobalDeleteEmpireBuildingMsg } from "./global_delete_empire_building_msg_type";
// Mark import as potentially unused
declare type __keep_GlobalDeleteEmpireBuildingMsg = GlobalDeleteEmpireBuildingMsg;
import { DeleteEmpireMsg } from "./delete_empire_msg_type";
// Mark import as potentially unused
declare type __keep_DeleteEmpireMsg = DeleteEmpireMsg;
import { EmpireClaimJoinMsg } from "./empire_claim_join_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireClaimJoinMsg = EmpireClaimJoinMsg;
import { EmpireResupplyNodeMsg } from "./empire_resupply_node_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireResupplyNodeMsg = EmpireResupplyNodeMsg;
import { EmpireCollectHexiteCapsuleMsg } from "./empire_collect_hexite_capsule_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireCollectHexiteCapsuleMsg = EmpireCollectHexiteCapsuleMsg;
import { EmpireStartSiegeMsg } from "./empire_start_siege_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireStartSiegeMsg = EmpireStartSiegeMsg;
import { EmpireSiegeAddSuppliesMsg } from "./empire_siege_add_supplies_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireSiegeAddSuppliesMsg = EmpireSiegeAddSuppliesMsg;
import { OnPlayerJoinedEmpireMsg } from "./on_player_joined_empire_msg_type";
// Mark import as potentially unused
declare type __keep_OnPlayerJoinedEmpireMsg = OnPlayerJoinedEmpireMsg;
import { OnPlayerLeftEmpireMsg } from "./on_player_left_empire_msg_type";
// Mark import as potentially unused
declare type __keep_OnPlayerLeftEmpireMsg = OnPlayerLeftEmpireMsg;
import { RegionDestroySiegeEngineMsg } from "./region_destroy_siege_engine_msg_type";
// Mark import as potentially unused
declare type __keep_RegionDestroySiegeEngineMsg = RegionDestroySiegeEngineMsg;
import { OnRegionPlayerCreatedMsg } from "./on_region_player_created_msg_type";
// Mark import as potentially unused
declare type __keep_OnRegionPlayerCreatedMsg = OnRegionPlayerCreatedMsg;
import { EmpireQueueSuppliesMsg } from "./empire_queue_supplies_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireQueueSuppliesMsg = EmpireQueueSuppliesMsg;
import { EmpireUpdateEmperorCrownMsg } from "./empire_update_emperor_crown_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireUpdateEmperorCrownMsg = EmpireUpdateEmperorCrownMsg;
import { EmpireRemoveCrownMsg } from "./empire_remove_crown_msg_type";
// Mark import as potentially unused
declare type __keep_EmpireRemoveCrownMsg = EmpireRemoveCrownMsg;
import { SignPlayerOutMsg } from "./sign_player_out_msg_type";
// Mark import as potentially unused
declare type __keep_SignPlayerOutMsg = SignPlayerOutMsg;
import { AdminBroadcastMessageMsg } from "./admin_broadcast_message_msg_type";
// Mark import as potentially unused
declare type __keep_AdminBroadcastMessageMsg = AdminBroadcastMessageMsg;
import { PlayerSkipQueueMsg } from "./player_skip_queue_msg_type";
// Mark import as potentially unused
declare type __keep_PlayerSkipQueueMsg = PlayerSkipQueueMsg;
import { GrantHubItemMsg } from "./grant_hub_item_msg_type";
// Mark import as potentially unused
declare type __keep_GrantHubItemMsg = GrantHubItemMsg;
import { RecoverDeployableMsg } from "./recover_deployable_msg_type";
// Mark import as potentially unused
declare type __keep_RecoverDeployableMsg = RecoverDeployableMsg;
import { OnDeployableRecoveredMsg } from "./on_deployable_recovered_msg_type";
// Mark import as potentially unused
declare type __keep_OnDeployableRecoveredMsg = OnDeployableRecoveredMsg;

import * as MessageContentsVariants from './message_contents_variants'

// The tagged union or sum type for the algebraic type `MessageContents`.
export type MessageContents = MessageContentsVariants.TableUpdate |
  MessageContentsVariants.TransferPlayerRequest |
  MessageContentsVariants.TransferPlayerHousingRequest |
  MessageContentsVariants.PlayerCreateRequest |
  MessageContentsVariants.UserUpdateRegionRequest |
  MessageContentsVariants.OnPlayerNameSetRequest |
  MessageContentsVariants.ClaimCreateEmpireSettlementState |
  MessageContentsVariants.OnClaimMembersChanged |
  MessageContentsVariants.EmpireCreateBuilding |
  MessageContentsVariants.OnEmpireBuildingDeleted |
  MessageContentsVariants.GlobalDeleteEmpireBuilding |
  MessageContentsVariants.DeleteEmpire |
  MessageContentsVariants.EmpireClaimJoin |
  MessageContentsVariants.EmpireResupplyNode |
  MessageContentsVariants.EmpireCollectHexiteCapsule |
  MessageContentsVariants.EmpireStartSiege |
  MessageContentsVariants.EmpireSiegeAddSupplies |
  MessageContentsVariants.OnPlayerJoinedEmpire |
  MessageContentsVariants.OnPlayerLeftEmpire |
  MessageContentsVariants.RegionDestroySiegeEngine |
  MessageContentsVariants.OnRegionPlayerCreated |
  MessageContentsVariants.EmpireQueueSupplies |
  MessageContentsVariants.EmpireUpdateEmperorCrown |
  MessageContentsVariants.EmpireRemoveCrown |
  MessageContentsVariants.SignPlayerOut |
  MessageContentsVariants.AdminBroadcastMessage |
  MessageContentsVariants.PlayerSkipQueue |
  MessageContentsVariants.GrantHubItem |
  MessageContentsVariants.RecoverDeployable |
  MessageContentsVariants.OnDeployableRecovered;

// A value with helper functions to construct the type.
export const MessageContents = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  TableUpdate: (value: InterModuleTableUpdates): MessageContents => ({ tag: "TableUpdate", value }),
  TransferPlayerRequest: (value: TransferPlayerMsg): MessageContents => ({ tag: "TransferPlayerRequest", value }),
  TransferPlayerHousingRequest: (value: TransferPlayerHousingMsg): MessageContents => ({ tag: "TransferPlayerHousingRequest", value }),
  PlayerCreateRequest: (value: PlayerCreateMsg): MessageContents => ({ tag: "PlayerCreateRequest", value }),
  UserUpdateRegionRequest: (value: UserUpdateRegionMsg): MessageContents => ({ tag: "UserUpdateRegionRequest", value }),
  OnPlayerNameSetRequest: (value: OnPlayerNameSetMsg): MessageContents => ({ tag: "OnPlayerNameSetRequest", value }),
  ClaimCreateEmpireSettlementState: (value: ClaimCreateEmpireSettlementMsg): MessageContents => ({ tag: "ClaimCreateEmpireSettlementState", value }),
  OnClaimMembersChanged: (value: OnClaimMembersChangedMsg): MessageContents => ({ tag: "OnClaimMembersChanged", value }),
  EmpireCreateBuilding: (value: EmpireCreateBuildingMsg): MessageContents => ({ tag: "EmpireCreateBuilding", value }),
  OnEmpireBuildingDeleted: (value: OnEmpireBuildingDeletedMsg): MessageContents => ({ tag: "OnEmpireBuildingDeleted", value }),
  GlobalDeleteEmpireBuilding: (value: GlobalDeleteEmpireBuildingMsg): MessageContents => ({ tag: "GlobalDeleteEmpireBuilding", value }),
  DeleteEmpire: (value: DeleteEmpireMsg): MessageContents => ({ tag: "DeleteEmpire", value }),
  EmpireClaimJoin: (value: EmpireClaimJoinMsg): MessageContents => ({ tag: "EmpireClaimJoin", value }),
  EmpireResupplyNode: (value: EmpireResupplyNodeMsg): MessageContents => ({ tag: "EmpireResupplyNode", value }),
  EmpireCollectHexiteCapsule: (value: EmpireCollectHexiteCapsuleMsg): MessageContents => ({ tag: "EmpireCollectHexiteCapsule", value }),
  EmpireStartSiege: (value: EmpireStartSiegeMsg): MessageContents => ({ tag: "EmpireStartSiege", value }),
  EmpireSiegeAddSupplies: (value: EmpireSiegeAddSuppliesMsg): MessageContents => ({ tag: "EmpireSiegeAddSupplies", value }),
  OnPlayerJoinedEmpire: (value: OnPlayerJoinedEmpireMsg): MessageContents => ({ tag: "OnPlayerJoinedEmpire", value }),
  OnPlayerLeftEmpire: (value: OnPlayerLeftEmpireMsg): MessageContents => ({ tag: "OnPlayerLeftEmpire", value }),
  RegionDestroySiegeEngine: (value: RegionDestroySiegeEngineMsg): MessageContents => ({ tag: "RegionDestroySiegeEngine", value }),
  OnRegionPlayerCreated: (value: OnRegionPlayerCreatedMsg): MessageContents => ({ tag: "OnRegionPlayerCreated", value }),
  EmpireQueueSupplies: (value: EmpireQueueSuppliesMsg): MessageContents => ({ tag: "EmpireQueueSupplies", value }),
  EmpireUpdateEmperorCrown: (value: EmpireUpdateEmperorCrownMsg): MessageContents => ({ tag: "EmpireUpdateEmperorCrown", value }),
  EmpireRemoveCrown: (value: EmpireRemoveCrownMsg): MessageContents => ({ tag: "EmpireRemoveCrown", value }),
  SignPlayerOut: (value: SignPlayerOutMsg): MessageContents => ({ tag: "SignPlayerOut", value }),
  AdminBroadcastMessage: (value: AdminBroadcastMessageMsg): MessageContents => ({ tag: "AdminBroadcastMessage", value }),
  PlayerSkipQueue: (value: PlayerSkipQueueMsg): MessageContents => ({ tag: "PlayerSkipQueue", value }),
  GrantHubItem: (value: GrantHubItemMsg): MessageContents => ({ tag: "GrantHubItem", value }),
  RecoverDeployable: (value: RecoverDeployableMsg): MessageContents => ({ tag: "RecoverDeployable", value }),
  OnDeployableRecovered: (value: OnDeployableRecoveredMsg): MessageContents => ({ tag: "OnDeployableRecovered", value }),

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "TableUpdate", algebraicType: InterModuleTableUpdates.getTypeScriptAlgebraicType() },
        { name: "TransferPlayerRequest", algebraicType: TransferPlayerMsg.getTypeScriptAlgebraicType() },
        { name: "TransferPlayerHousingRequest", algebraicType: TransferPlayerHousingMsg.getTypeScriptAlgebraicType() },
        { name: "PlayerCreateRequest", algebraicType: PlayerCreateMsg.getTypeScriptAlgebraicType() },
        { name: "UserUpdateRegionRequest", algebraicType: UserUpdateRegionMsg.getTypeScriptAlgebraicType() },
        { name: "OnPlayerNameSetRequest", algebraicType: OnPlayerNameSetMsg.getTypeScriptAlgebraicType() },
        { name: "ClaimCreateEmpireSettlementState", algebraicType: ClaimCreateEmpireSettlementMsg.getTypeScriptAlgebraicType() },
        { name: "OnClaimMembersChanged", algebraicType: OnClaimMembersChangedMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireCreateBuilding", algebraicType: EmpireCreateBuildingMsg.getTypeScriptAlgebraicType() },
        { name: "OnEmpireBuildingDeleted", algebraicType: OnEmpireBuildingDeletedMsg.getTypeScriptAlgebraicType() },
        { name: "GlobalDeleteEmpireBuilding", algebraicType: GlobalDeleteEmpireBuildingMsg.getTypeScriptAlgebraicType() },
        { name: "DeleteEmpire", algebraicType: DeleteEmpireMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireClaimJoin", algebraicType: EmpireClaimJoinMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireResupplyNode", algebraicType: EmpireResupplyNodeMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireCollectHexiteCapsule", algebraicType: EmpireCollectHexiteCapsuleMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireStartSiege", algebraicType: EmpireStartSiegeMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireSiegeAddSupplies", algebraicType: EmpireSiegeAddSuppliesMsg.getTypeScriptAlgebraicType() },
        { name: "OnPlayerJoinedEmpire", algebraicType: OnPlayerJoinedEmpireMsg.getTypeScriptAlgebraicType() },
        { name: "OnPlayerLeftEmpire", algebraicType: OnPlayerLeftEmpireMsg.getTypeScriptAlgebraicType() },
        { name: "RegionDestroySiegeEngine", algebraicType: RegionDestroySiegeEngineMsg.getTypeScriptAlgebraicType() },
        { name: "OnRegionPlayerCreated", algebraicType: OnRegionPlayerCreatedMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireQueueSupplies", algebraicType: EmpireQueueSuppliesMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireUpdateEmperorCrown", algebraicType: EmpireUpdateEmperorCrownMsg.getTypeScriptAlgebraicType() },
        { name: "EmpireRemoveCrown", algebraicType: EmpireRemoveCrownMsg.getTypeScriptAlgebraicType() },
        { name: "SignPlayerOut", algebraicType: SignPlayerOutMsg.getTypeScriptAlgebraicType() },
        { name: "AdminBroadcastMessage", algebraicType: AdminBroadcastMessageMsg.getTypeScriptAlgebraicType() },
        { name: "PlayerSkipQueue", algebraicType: PlayerSkipQueueMsg.getTypeScriptAlgebraicType() },
        { name: "GrantHubItem", algebraicType: GrantHubItemMsg.getTypeScriptAlgebraicType() },
        { name: "RecoverDeployable", algebraicType: RecoverDeployableMsg.getTypeScriptAlgebraicType() },
        { name: "OnDeployableRecovered", algebraicType: OnDeployableRecoveredMsg.getTypeScriptAlgebraicType() },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: MessageContents): void {
      __AlgebraicTypeValue.serializeValue(writer, MessageContents.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): MessageContents {
      return __AlgebraicTypeValue.deserializeValue(reader, MessageContents.getTypeScriptAlgebraicType());
  },

}

export default MessageContents;


