// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type MobileEntityState = {
  entityId: bigint,
  chunkIndex: bigint,
  timestamp: bigint,
  locationX: number,
  locationZ: number,
  destinationX: number,
  destinationZ: number,
  dimension: number,
  isRunning: boolean,
  pad1: number,
  pad2: number,
  pad3: number,
};
/**
 * An object for generated helper functions.
 */
export const MobileEntityState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "chunkIndex", algebraicType: __AlgebraicTypeValue.U64},
        { name: "timestamp", algebraicType: __AlgebraicTypeValue.U64},
        { name: "locationX", algebraicType: __AlgebraicTypeValue.I32},
        { name: "locationZ", algebraicType: __AlgebraicTypeValue.I32},
        { name: "destinationX", algebraicType: __AlgebraicTypeValue.I32},
        { name: "destinationZ", algebraicType: __AlgebraicTypeValue.I32},
        { name: "dimension", algebraicType: __AlgebraicTypeValue.U32},
        { name: "isRunning", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "pad1", algebraicType: __AlgebraicTypeValue.U8},
        { name: "pad2", algebraicType: __AlgebraicTypeValue.U8},
        { name: "pad3", algebraicType: __AlgebraicTypeValue.U8},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: MobileEntityState): void {
    __AlgebraicTypeValue.serializeValue(writer, MobileEntityState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): MobileEntityState {
    return __AlgebraicTypeValue.deserializeValue(reader, MobileEntityState.getTypeScriptAlgebraicType());
  },

}

export default MobileEntityState;


