// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ModViolationState } from "./mod_violation_state_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `mod_violation_state`.
 *
 * Obtain a handle from the [`modViolationState`] property on [`RemoteTables`],
 * like `ctx.db.modViolationState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.modViolationState.on_insert(...)`.
 */
export class ModViolationStateTableHandle {
  tableCache: TableCache<ModViolationState>;

  constructor(tableCache: TableCache<ModViolationState>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ModViolationState> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `violationType` unique index on the table `mod_violation_state`,
   * which allows point queries on the field of the same name
   * via the [`ModViolationStateViolationTypeUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.modViolationState.violationType().find(...)`.
   *
   * Get a handle on the `violationType` unique index on the table `mod_violation_state`.
   */
  violationType = {
    // Find the subscribed row whose `violationType` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ModViolationState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.violationType, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ModViolationState) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ModViolationState) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ModViolationState) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ModViolationState) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ModViolationState, newRow: ModViolationState) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ModViolationState, newRow: ModViolationState) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
