// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DeployableStateV2 as __DeployableStateV2 } from "./deployable_state_v_2_type";
import { TradeOrderState as __TradeOrderState } from "./trade_order_state_type";

export type OnDeployableRecoveredMsgV2 = {
  playerEntityId: bigint,
  deployableEntityId: bigint,
  deployableDescId: number,
  deployableState: __DeployableStateV2,
  tradeOrders: __TradeOrderState[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace OnDeployableRecoveredMsgV2 {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("playerEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("deployableEntityId", AlgebraicType.createU64Type()),
      new ProductTypeElement("deployableDescId", AlgebraicType.createI32Type()),
      new ProductTypeElement("deployableState", __DeployableStateV2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("tradeOrders", AlgebraicType.createArrayType(__TradeOrderState.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: OnDeployableRecoveredMsgV2): void {
    OnDeployableRecoveredMsgV2.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): OnDeployableRecoveredMsgV2 {
    return OnDeployableRecoveredMsgV2.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


