// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type OnDurabilityZeroTimer = {
  scheduledId: bigint,
  scheduledAt: { tag: "Interval", value: __TimeDuration } | { tag: "Time", value: __Timestamp },
  playerEntityId: bigint,
  brokenItemId: number,
  convertInto: number,
  stillEquipped: boolean,
  addedToInventory: boolean,
};
/**
 * An object for generated helper functions.
 */
export const OnDurabilityZeroTimer = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "scheduledId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "scheduledAt", algebraicType: __AlgebraicTypeValue.createScheduleAtType()},
        { name: "playerEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "brokenItemId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "convertInto", algebraicType: __AlgebraicTypeValue.I32},
        { name: "stillEquipped", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "addedToInventory", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: OnDurabilityZeroTimer): void {
    __AlgebraicTypeValue.serializeValue(writer, OnDurabilityZeroTimer.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): OnDurabilityZeroTimer {
    return __AlgebraicTypeValue.deserializeValue(reader, OnDurabilityZeroTimer.getTypeScriptAlgebraicType());
  },

}

export default OnDurabilityZeroTimer;


