// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { PassiveCraftStatus } from "./passive_craft_status_type";
// Mark import as potentially unused
declare type __keep_PassiveCraftStatus = PassiveCraftStatus;


export type PassiveCraftState = {
  entityId: bigint,
  ownerEntityId: bigint,
  recipeId: number,
  buildingEntityId: bigint,
  timestamp: __Timestamp,
  status: PassiveCraftStatus,
  slot: number | undefined,
};
/**
 * An object for generated helper functions.
 */
export const PassiveCraftState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "ownerEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "recipeId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "buildingEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "timestamp", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "status", algebraicType: PassiveCraftStatus.getTypeScriptAlgebraicType()},
        { name: "slot", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U32)},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PassiveCraftState): void {
    __AlgebraicTypeValue.serializeValue(writer, PassiveCraftState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PassiveCraftState {
    return __AlgebraicTypeValue.deserializeValue(reader, PassiveCraftState.getTypeScriptAlgebraicType());
  },

}

export default PassiveCraftState;


