// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { CsvStatEntry } from "./csv_stat_entry_type";
// Mark import as potentially unused
declare type __keep_CsvStatEntry = CsvStatEntry;
import { InputItemStack } from "./input_item_stack_type";
// Mark import as potentially unused
declare type __keep_InputItemStack = InputItemStack;
import { ExperienceStackF32 } from "./experience_stack_f_32_type";
// Mark import as potentially unused
declare type __keep_ExperienceStackF32 = ExperienceStackF32;


export type PavingTileDesc = {
  id: number,
  name: string,
  consumedItemStacks: InputItemStack[],
  inputCargoId: number,
  inputCargoDiscoveryScore: number,
  experiencePerProgress: ExperienceStackF32[],
  discoveryTriggers: number[],
  requiredKnowledges: number[],
  fullDiscoveryScore: number,
  pavingDuration: number,
  prefabAddress: string,
  tier: number,
  statEffects: CsvStatEntry[],
  iconAddress: string,
  description: string,
};
/**
 * An object for generated helper functions.
 */
export const PavingTileDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "consumedItemStacks", algebraicType: __AlgebraicTypeValue.Array(InputItemStack.getTypeScriptAlgebraicType())},
        { name: "inputCargoId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "inputCargoDiscoveryScore", algebraicType: __AlgebraicTypeValue.I32},
        { name: "experiencePerProgress", algebraicType: __AlgebraicTypeValue.Array(ExperienceStackF32.getTypeScriptAlgebraicType())},
        { name: "discoveryTriggers", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "requiredKnowledges", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "fullDiscoveryScore", algebraicType: __AlgebraicTypeValue.I32},
        { name: "pavingDuration", algebraicType: __AlgebraicTypeValue.F32},
        { name: "prefabAddress", algebraicType: __AlgebraicTypeValue.String},
        { name: "tier", algebraicType: __AlgebraicTypeValue.I32},
        { name: "statEffects", algebraicType: __AlgebraicTypeValue.Array(CsvStatEntry.getTypeScriptAlgebraicType())},
        { name: "iconAddress", algebraicType: __AlgebraicTypeValue.String},
        { name: "description", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PavingTileDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, PavingTileDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PavingTileDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, PavingTileDesc.getTypeScriptAlgebraicType());
  },

}

export default PavingTileDesc;


