// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Rarity as __Rarity } from "./rarity_type";

export type PlaceableDesc = {
  id: number,
  name: string,
  tag: string,
  tier: number,
  description: string,
  rarity: __Rarity,
  modelAssetName: string,
  iconAssetName: string,
  maxHealth: number,
  visibleToOthers: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlaceableDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("tag", AlgebraicType.createStringType()),
      new ProductTypeElement("tier", AlgebraicType.createI32Type()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("rarity", __Rarity.getTypeScriptAlgebraicType()),
      new ProductTypeElement("modelAssetName", AlgebraicType.createStringType()),
      new ProductTypeElement("iconAssetName", AlgebraicType.createStringType()),
      new ProductTypeElement("maxHealth", AlgebraicType.createI32Type()),
      new ProductTypeElement("visibleToOthers", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlaceableDesc): void {
    PlaceableDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlaceableDesc {
    return PlaceableDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


