// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PlaceablePlaceStartEvent } from "./placeable_place_start_event_type";
import { PlayerPlaceablePlaceRequest as __PlayerPlaceablePlaceRequest } from "./player_placeable_place_request_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `placeable_place_start_event`.
 *
 * Obtain a handle from the [`placeablePlaceStartEvent`] property on [`RemoteTables`],
 * like `ctx.db.placeablePlaceStartEvent`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.placeablePlaceStartEvent.on_insert(...)`.
 */
export class PlaceablePlaceStartEventTableHandle {
  tableCache: TableCache<PlaceablePlaceStartEvent>;

  constructor(tableCache: TableCache<PlaceablePlaceStartEvent>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PlaceablePlaceStartEvent> {
    return this.tableCache.iter();
  }

  onInsert = (cb: (ctx: EventContext, row: PlaceablePlaceStartEvent) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PlaceablePlaceStartEvent) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PlaceablePlaceStartEvent) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PlaceablePlaceStartEvent) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }
}
