// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::growth_timer_type::GrowthTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceableGrowthScheduledArgs {
    pub timer: GrowthTimer,
}

impl From<PlaceableGrowthScheduledArgs> for super::Reducer {
    fn from(args: PlaceableGrowthScheduledArgs) -> Self {
        Self::PlaceableGrowthScheduled { timer: args.timer }
    }
}

impl __sdk::InModule for PlaceableGrowthScheduledArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `placeable_growth_scheduled`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait placeable_growth_scheduled {
    /// Request that the remote module invoke the reducer `placeable_growth_scheduled` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`placeable_growth_scheduled:placeable_growth_scheduled_then`] to run a callback after the reducer completes.
    fn placeable_growth_scheduled(&self, timer: GrowthTimer) -> __sdk::Result<()> {
        self.placeable_growth_scheduled_then(timer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `placeable_growth_scheduled` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn placeable_growth_scheduled_then(
        &self,
        timer: GrowthTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl placeable_growth_scheduled for super::RemoteReducers {
    fn placeable_growth_scheduled_then(
        &self,
        timer: GrowthTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlaceableGrowthScheduledArgs { timer }, callback)
    }
}
