// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PlayerPlaceablePlaceRequest as __PlayerPlaceablePlaceRequest } from "./player_placeable_place_request_type";

export type PlaceablePlaceStartEvent = {
  actorId: bigint,
  request: __PlayerPlaceablePlaceRequest,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlaceablePlaceStartEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("actorId", AlgebraicType.createU64Type()),
      new ProductTypeElement("request", __PlayerPlaceablePlaceRequest.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlaceablePlaceStartEvent): void {
    PlaceablePlaceStartEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlaceablePlaceStartEvent {
    return PlaceablePlaceStartEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


