// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_signed_out_event_type::PlayerSignedOutEvent;
use super::player_signed_out_reason_type::PlayerSignedOutReason;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_signed_out_event`.
///
/// Obtain a handle from the [`PlayerSignedOutEventTableAccess::player_signed_out_event`] method on [`super::RemoteTables`],
/// like `ctx.db.player_signed_out_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_signed_out_event().on_insert(...)`.
pub struct PlayerSignedOutEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerSignedOutEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_signed_out_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerSignedOutEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerSignedOutEventTableHandle`], which mediates access to the table `player_signed_out_event`.
    fn player_signed_out_event(&self) -> PlayerSignedOutEventTableHandle<'_>;
}

impl PlayerSignedOutEventTableAccess for super::RemoteTables {
    fn player_signed_out_event(&self) -> PlayerSignedOutEventTableHandle<'_> {
        PlayerSignedOutEventTableHandle {
            imp: self
                .imp
                .get_table::<PlayerSignedOutEvent>("player_signed_out_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerSignedOutEventInsertCallbackId(__sdk::CallbackId);
pub struct PlayerSignedOutEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerSignedOutEventTableHandle<'ctx> {
    type Row = PlayerSignedOutEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerSignedOutEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerSignedOutEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSignedOutEventInsertCallbackId {
        PlayerSignedOutEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerSignedOutEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerSignedOutEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerSignedOutEventDeleteCallbackId {
        PlayerSignedOutEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerSignedOutEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerSignedOutEvent>("player_signed_out_event");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerSignedOutEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerSignedOutEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerSignedOutEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_signed_out_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerSignedOutEvent`.
    fn player_signed_out_event(&self) -> __sdk::__query_builder::Table<PlayerSignedOutEvent>;
}

impl player_signed_out_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_signed_out_event(&self) -> __sdk::__query_builder::Table<PlayerSignedOutEvent> {
        __sdk::__query_builder::Table::new("player_signed_out_event")
    }
}
