// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as PlayerActionTypeVariants from './player_action_type_variants'

// The tagged union or sum type for the algebraic type `PlayerActionType`.
export type PlayerActionType = PlayerActionTypeVariants.None |
  PlayerActionTypeVariants.Attack |
  PlayerActionTypeVariants.DestroyPaving |
  PlayerActionTypeVariants.StationaryEmote |
  PlayerActionTypeVariants.Extract |
  PlayerActionTypeVariants.PaveTile |
  PlayerActionTypeVariants.SpawnCargo |
  PlayerActionTypeVariants.Build |
  PlayerActionTypeVariants.Deconstruct |
  PlayerActionTypeVariants.RepairBuilding |
  PlayerActionTypeVariants.ResupplyClaim |
  PlayerActionTypeVariants.CargoPickUp |
  PlayerActionTypeVariants.Terraform |
  PlayerActionTypeVariants.DeployDeployable |
  PlayerActionTypeVariants.StoreDeployable |
  PlayerActionTypeVariants.Sleep |
  PlayerActionTypeVariants.Teleport |
  PlayerActionTypeVariants.Death |
  PlayerActionTypeVariants.Climb |
  PlayerActionTypeVariants.UseItem |
  PlayerActionTypeVariants.Craft |
  PlayerActionTypeVariants.ConvertItems |
  PlayerActionTypeVariants.PlayerMove |
  PlayerActionTypeVariants.DeployableMove |
  PlayerActionTypeVariants.ResupplyEmpireNode |
  PlayerActionTypeVariants.SetHome |
  PlayerActionTypeVariants.UseElevator |
  PlayerActionTypeVariants.MobileEmote |
  PlayerActionTypeVariants.PlacePillarShaping |
  PlayerActionTypeVariants.DestroyPillarShaping;

// A value with helper functions to construct the type.
export const PlayerActionType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  None: { tag: "None" } as const,
  Attack: { tag: "Attack" } as const,
  DestroyPaving: { tag: "DestroyPaving" } as const,
  StationaryEmote: { tag: "StationaryEmote" } as const,
  Extract: { tag: "Extract" } as const,
  PaveTile: { tag: "PaveTile" } as const,
  SpawnCargo: { tag: "SpawnCargo" } as const,
  Build: { tag: "Build" } as const,
  Deconstruct: { tag: "Deconstruct" } as const,
  RepairBuilding: { tag: "RepairBuilding" } as const,
  ResupplyClaim: { tag: "ResupplyClaim" } as const,
  CargoPickUp: { tag: "CargoPickUp" } as const,
  Terraform: { tag: "Terraform" } as const,
  DeployDeployable: { tag: "DeployDeployable" } as const,
  StoreDeployable: { tag: "StoreDeployable" } as const,
  Sleep: { tag: "Sleep" } as const,
  Teleport: { tag: "Teleport" } as const,
  Death: { tag: "Death" } as const,
  Climb: { tag: "Climb" } as const,
  UseItem: { tag: "UseItem" } as const,
  Craft: { tag: "Craft" } as const,
  ConvertItems: { tag: "ConvertItems" } as const,
  PlayerMove: { tag: "PlayerMove" } as const,
  DeployableMove: { tag: "DeployableMove" } as const,
  ResupplyEmpireNode: { tag: "ResupplyEmpireNode" } as const,
  SetHome: { tag: "SetHome" } as const,
  UseElevator: { tag: "UseElevator" } as const,
  MobileEmote: { tag: "MobileEmote" } as const,
  PlacePillarShaping: { tag: "PlacePillarShaping" } as const,
  DestroyPillarShaping: { tag: "DestroyPillarShaping" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "None", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Attack", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DestroyPaving", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "StationaryEmote", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Extract", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PaveTile", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SpawnCargo", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Build", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Deconstruct", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "RepairBuilding", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ResupplyClaim", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "CargoPickUp", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Terraform", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DeployDeployable", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "StoreDeployable", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Sleep", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Teleport", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Death", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Climb", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "UseItem", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Craft", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ConvertItems", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PlayerMove", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DeployableMove", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "ResupplyEmpireNode", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "SetHome", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "UseElevator", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MobileEmote", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "PlacePillarShaping", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "DestroyPillarShaping", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PlayerActionType): void {
      __AlgebraicTypeValue.serializeValue(writer, PlayerActionType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerActionType {
      return __AlgebraicTypeValue.deserializeValue(reader, PlayerActionType.getTypeScriptAlgebraicType());
  },

}

export default PlayerActionType;


