// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type None = { tag: "None" };
export type Attack = { tag: "Attack" };
export type DestroyPaving = { tag: "DestroyPaving" };
export type StationaryEmote = { tag: "StationaryEmote" };
export type Extract = { tag: "Extract" };
export type PaveTile = { tag: "PaveTile" };
export type SpawnCargo = { tag: "SpawnCargo" };
export type Build = { tag: "Build" };
export type Deconstruct = { tag: "Deconstruct" };
export type RepairBuilding = { tag: "RepairBuilding" };
export type ResupplyClaim = { tag: "ResupplyClaim" };
export type CargoPickUp = { tag: "CargoPickUp" };
export type Terraform = { tag: "Terraform" };
export type DeployDeployable = { tag: "DeployDeployable" };
export type StoreDeployable = { tag: "StoreDeployable" };
export type Sleep = { tag: "Sleep" };
export type Teleport = { tag: "Teleport" };
export type Death = { tag: "Death" };
export type Climb = { tag: "Climb" };
export type UseItem = { tag: "UseItem" };
export type Craft = { tag: "Craft" };
export type ConvertItems = { tag: "ConvertItems" };
export type PlayerMove = { tag: "PlayerMove" };
export type DeployableMove = { tag: "DeployableMove" };
export type ResupplyEmpireNode = { tag: "ResupplyEmpireNode" };
export type SetHome = { tag: "SetHome" };
export type UseElevator = { tag: "UseElevator" };
export type MobileEmote = { tag: "MobileEmote" };
export type PlacePillarShaping = { tag: "PlacePillarShaping" };
export type DestroyPillarShaping = { tag: "DestroyPillarShaping" };

