// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { PlayerActionLayer } from "./player_action_layer_type";
// Mark import as potentially unused
declare type __keep_PlayerActionLayer = PlayerActionLayer;
import { PlayerActionType } from "./player_action_type_type";
// Mark import as potentially unused
declare type __keep_PlayerActionType = PlayerActionType;
import { PlayerActionResult } from "./player_action_result_type";
// Mark import as potentially unused
declare type __keep_PlayerActionResult = PlayerActionResult;


export type PlayerActionState = {
  autoId: bigint,
  chunkIndex: bigint,
  entityId: bigint,
  startTime: bigint,
  duration: bigint,
  target: bigint | undefined,
  recipeId: number | undefined,
  actionType: PlayerActionType,
  layer: PlayerActionLayer,
  lastActionResult: PlayerActionResult,
  clientCancel: boolean,
  pad: number,
};
/**
 * An object for generated helper functions.
 */
export const PlayerActionState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "autoId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "chunkIndex", algebraicType: __AlgebraicTypeValue.U64},
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "startTime", algebraicType: __AlgebraicTypeValue.U64},
        { name: "duration", algebraicType: __AlgebraicTypeValue.U64},
        { name: "target", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.U64)},
        { name: "recipeId", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I32)},
        { name: "actionType", algebraicType: PlayerActionType.getTypeScriptAlgebraicType()},
        { name: "layer", algebraicType: PlayerActionLayer.getTypeScriptAlgebraicType()},
        { name: "lastActionResult", algebraicType: PlayerActionResult.getTypeScriptAlgebraicType()},
        { name: "clientCancel", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "pad", algebraicType: __AlgebraicTypeValue.U32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PlayerActionState): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerActionState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerActionState {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerActionState.getTypeScriptAlgebraicType());
  },

}

export default PlayerActionState;


