// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type PlayerHousingState = {
  entityId: bigint,
  entranceBuildingEntityId: bigint,
  networkEntityId: bigint,
  exitPortalEntityId: bigint,
  rank: number,
  lockedUntil: __Timestamp,
  isEmpty: boolean,
  regionIndex: number,
};
/**
 * An object for generated helper functions.
 */
export const PlayerHousingState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "entranceBuildingEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "networkEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "exitPortalEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "rank", algebraicType: __AlgebraicTypeValue.I32},
        { name: "lockedUntil", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "isEmpty", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "regionIndex", algebraicType: __AlgebraicTypeValue.U8},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: PlayerHousingState): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerHousingState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerHousingState {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerHousingState.getTypeScriptAlgebraicType());
  },

}

export default PlayerHousingState;


