// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_set_name_outcome_event_type::PlayerSetNameOutcomeEvent;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerSetNameOutcomeEventReducerArgs {
    pub timer: PlayerSetNameOutcomeEvent,
}

impl From<PlayerSetNameOutcomeEventReducerArgs> for super::Reducer {
    fn from(args: PlayerSetNameOutcomeEventReducerArgs) -> Self {
        Self::PlayerSetNameOutcomeEventReducer { timer: args.timer }
    }
}

impl __sdk::InModule for PlayerSetNameOutcomeEventReducerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_set_name_outcome_event_reducer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_set_name_outcome_event_reducer {
    /// Request that the remote module invoke the reducer `player_set_name_outcome_event_reducer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`player_set_name_outcome_event_reducer:player_set_name_outcome_event_reducer_then`] to run a callback after the reducer completes.
    fn player_set_name_outcome_event_reducer(
        &self,
        timer: PlayerSetNameOutcomeEvent,
    ) -> __sdk::Result<()> {
        self.player_set_name_outcome_event_reducer_then(timer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `player_set_name_outcome_event_reducer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn player_set_name_outcome_event_reducer_then(
        &self,
        timer: PlayerSetNameOutcomeEvent,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl player_set_name_outcome_event_reducer for super::RemoteReducers {
    fn player_set_name_outcome_event_reducer_then(
        &self,
        timer: PlayerSetNameOutcomeEvent,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlayerSetNameOutcomeEventReducerArgs { timer }, callback)
    }
}
