// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::move_validation_params_desc_type::MoveValidationParamsDesc;
use super::private_parameters_desc_type::PrivateParametersDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `private_parameters_desc`.
///
/// Obtain a handle from the [`PrivateParametersDescTableAccess::private_parameters_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.private_parameters_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.private_parameters_desc().on_insert(...)`.
pub struct PrivateParametersDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<PrivateParametersDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `private_parameters_desc`.
pub struct PrivateParametersDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PrivateParametersDescTableAccessor {
    type Row = PrivateParametersDesc;
    type Handle<'db> = PrivateParametersDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.private_parameters_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `private_parameters_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PrivateParametersDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PrivateParametersDescTableHandle`], which mediates access to the table `private_parameters_desc`.
    fn private_parameters_desc(&self) -> PrivateParametersDescTableHandle<'_>;
}

impl PrivateParametersDescTableAccess for super::RemoteTables {
    fn private_parameters_desc(&self) -> PrivateParametersDescTableHandle<'_> {
        PrivateParametersDescTableHandle {
            imp: self
                .imp
                .get_table::<PrivateParametersDesc>("private_parameters_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PrivateParametersDescInsertCallbackId(__sdk::CallbackId);
pub struct PrivateParametersDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PrivateParametersDescTableHandle<'ctx> {
    type Row = PrivateParametersDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PrivateParametersDesc> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PrivateParametersDescTableHandle<'ctx> {
    type Row = PrivateParametersDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PrivateParametersDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PrivateParametersDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescInsertCallbackId {
        PrivateParametersDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PrivateParametersDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PrivateParametersDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescDeleteCallbackId {
        PrivateParametersDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PrivateParametersDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PrivateParametersDescTableHandle<'ctx> {
    type InsertCallbackId = PrivateParametersDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescInsertCallbackId {
        PrivateParametersDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PrivateParametersDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PrivateParametersDescTableHandle<'ctx> {
    type DeleteCallbackId = PrivateParametersDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescDeleteCallbackId {
        PrivateParametersDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PrivateParametersDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PrivateParametersDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PrivateParametersDescTableHandle<'ctx> {
    type UpdateCallbackId = PrivateParametersDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescUpdateCallbackId {
        PrivateParametersDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PrivateParametersDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PrivateParametersDescTableHandle<'ctx> {
    type UpdateCallbackId = PrivateParametersDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PrivateParametersDescUpdateCallbackId {
        PrivateParametersDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PrivateParametersDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `version` unique index on the table `private_parameters_desc`,
/// which allows point queries on the field of the same name
/// via the [`PrivateParametersDescVersionUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.private_parameters_desc().version().find(...)`.
pub struct PrivateParametersDescVersionUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PrivateParametersDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PrivateParametersDescTableHandle<'ctx> {
    /// Get a handle on the `version` unique index on the table `private_parameters_desc`.
    pub fn version(&self) -> PrivateParametersDescVersionUnique<'ctx> {
        PrivateParametersDescVersionUnique {
            imp: self.imp.get_unique_constraint::<i32>("version"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PrivateParametersDescVersionUnique<'ctx> {
    /// Find the subscribed row whose `version` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<PrivateParametersDesc> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PrivateParametersDesc>("private_parameters_desc");
    _table.add_unique_constraint::<i32>("version", |row| &row.version);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PrivateParametersDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PrivateParametersDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PrivateParametersDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait private_parameters_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PrivateParametersDesc`.
    fn private_parameters_desc(&self) -> __sdk::__query_builder::Table<PrivateParametersDesc>;
}

impl private_parameters_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn private_parameters_desc(&self) -> __sdk::__query_builder::Table<PrivateParametersDesc> {
        __sdk::__query_builder::Table::new("private_parameters_desc")
    }
}
