// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProspectCancelArgs {}

impl From<ProspectCancelArgs> for super::Reducer {
    fn from(args: ProspectCancelArgs) -> Self {
        Self::ProspectCancel
    }
}

impl __sdk::InModule for ProspectCancelArgs {
    type Module = super::RemoteModule;
}

pub struct ProspectCancelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prospect_cancel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prospect_cancel {
    /// Request that the remote module invoke the reducer `prospect_cancel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_prospect_cancel`] callbacks.
    fn prospect_cancel(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `prospect_cancel`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProspectCancelCallbackId`] can be passed to [`Self::remove_on_prospect_cancel`]
    /// to cancel the callback.
    fn on_prospect_cancel(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ProspectCancelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_prospect_cancel`],
    /// causing it not to run in the future.
    fn remove_on_prospect_cancel(&self, callback: ProspectCancelCallbackId);
}

impl prospect_cancel for super::RemoteReducers {
    fn prospect_cancel(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("prospect_cancel", ProspectCancelArgs {})
    }
    fn on_prospect_cancel(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ProspectCancelCallbackId {
        ProspectCancelCallbackId(self.imp.on_reducer(
            "prospect_cancel",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ProspectCancel {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_prospect_cancel(&self, callback: ProspectCancelCallbackId) {
        self.imp.remove_on_reducer("prospect_cancel", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `prospect_cancel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_prospect_cancel {
    /// Set the call-reducer flags for the reducer `prospect_cancel` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn prospect_cancel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_prospect_cancel for super::SetReducerFlags {
    fn prospect_cancel(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("prospect_cancel", flags);
    }
}
