// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { ProbabilisticItemStack as __ProbabilisticItemStack } from "./probabilistic_item_stack_type";

export type QuestDropDesc = {
  id: number,
  extractionId: number,
  enemyId: number,
  itemListId: number,
  requiredQuestId: number,
  requiredStageId: number,
  itemDrop: __ProbabilisticItemStack,
};

/**
 * A namespace for generated helper functions.
 */
export namespace QuestDropDesc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createI32Type()),
      new ProductTypeElement("extractionId", AlgebraicType.createI32Type()),
      new ProductTypeElement("enemyId", AlgebraicType.createI32Type()),
      new ProductTypeElement("itemListId", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredQuestId", AlgebraicType.createI32Type()),
      new ProductTypeElement("requiredStageId", AlgebraicType.createI32Type()),
      new ProductTypeElement("itemDrop", __ProbabilisticItemStack.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: QuestDropDesc): void {
    QuestDropDesc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): QuestDropDesc {
    return QuestDropDesc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


