// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { RegionControlInfo } from "./region_control_info_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `region_control_info`.
 *
 * Obtain a handle from the [`regionControlInfo`] property on [`RemoteTables`],
 * like `ctx.db.regionControlInfo`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.regionControlInfo.on_insert(...)`.
 */
export class RegionControlInfoTableHandle {
  tableCache: TableCache<RegionControlInfo>;

  constructor(tableCache: TableCache<RegionControlInfo>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<RegionControlInfo> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `regionId` unique index on the table `region_control_info`,
   * which allows point queries on the field of the same name
   * via the [`RegionControlInfoRegionIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.regionControlInfo.regionId().find(...)`.
   *
   * Get a handle on the `regionId` unique index on the table `region_control_info`.
   */
  regionId = {
    // Find the subscribed row whose `regionId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): RegionControlInfo | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.regionId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: RegionControlInfo) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: RegionControlInfo) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: RegionControlInfo) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: RegionControlInfo) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: RegionControlInfo, newRow: RegionControlInfo) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: RegionControlInfo, newRow: RegionControlInfo) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
