// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::region_population_loop_timer_type::RegionPopulationLoopTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegionPopuplationAgentLoopArgs {
    pub timer: RegionPopulationLoopTimer,
}

impl From<RegionPopuplationAgentLoopArgs> for super::Reducer {
    fn from(args: RegionPopuplationAgentLoopArgs) -> Self {
        Self::RegionPopuplationAgentLoop { timer: args.timer }
    }
}

impl __sdk::InModule for RegionPopuplationAgentLoopArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `region_popuplation_agent_loop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait region_popuplation_agent_loop {
    /// Request that the remote module invoke the reducer `region_popuplation_agent_loop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`region_popuplation_agent_loop:region_popuplation_agent_loop_then`] to run a callback after the reducer completes.
    fn region_popuplation_agent_loop(&self, timer: RegionPopulationLoopTimer) -> __sdk::Result<()> {
        self.region_popuplation_agent_loop_then(timer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `region_popuplation_agent_loop` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn region_popuplation_agent_loop_then(
        &self,
        timer: RegionPopulationLoopTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl region_popuplation_agent_loop for super::RemoteReducers {
    fn region_popuplation_agent_loop_then(
        &self,
        timer: RegionPopulationLoopTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegionPopuplationAgentLoopArgs { timer }, callback)
    }
}
