// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type RegionModerationConfigState = {
  id: number,
  maxMessagesPerTimePeriod: number,
  rateLimitWindowSec: number,
  newAccountMinPlaytimeSec: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace RegionModerationConfigState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU8Type()),
      new ProductTypeElement("maxMessagesPerTimePeriod", AlgebraicType.createU32Type()),
      new ProductTypeElement("rateLimitWindowSec", AlgebraicType.createI32Type()),
      new ProductTypeElement("newAccountMinPlaytimeSec", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: RegionModerationConfigState): void {
    RegionModerationConfigState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): RegionModerationConfigState {
    return RegionModerationConfigState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


