// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveOfficialTranslatorArgs {
    pub player_entity_id: u64,
    pub lang: String,
}

impl From<RemoveOfficialTranslatorArgs> for super::Reducer {
    fn from(args: RemoveOfficialTranslatorArgs) -> Self {
        Self::RemoveOfficialTranslator {
            player_entity_id: args.player_entity_id,
            lang: args.lang,
        }
    }
}

impl __sdk::InModule for RemoveOfficialTranslatorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_official_translator`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_official_translator {
    /// Request that the remote module invoke the reducer `remove_official_translator` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`remove_official_translator:remove_official_translator_then`] to run a callback after the reducer completes.
    fn remove_official_translator(&self, player_entity_id: u64, lang: String) -> __sdk::Result<()> {
        self.remove_official_translator_then(player_entity_id, lang, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `remove_official_translator` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn remove_official_translator_then(
        &self,
        player_entity_id: u64,
        lang: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl remove_official_translator for super::RemoteReducers {
    fn remove_official_translator_then(
        &self,
        player_entity_id: u64,
        lang: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RemoveOfficialTranslatorArgs {
                player_entity_id,
                lang,
            },
            callback,
        )
    }
}
