// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type ResourceDestroyBuildingOutcome = {
  probability: number,
  buildingId: number,
  radiusMin: number,
  radiusMax: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ResourceDestroyBuildingOutcome {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("probability", AlgebraicType.createF32Type()),
      new ProductTypeElement("buildingId", AlgebraicType.createI32Type()),
      new ProductTypeElement("radiusMin", AlgebraicType.createI32Type()),
      new ProductTypeElement("radiusMax", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ResourceDestroyBuildingOutcome): void {
    ResourceDestroyBuildingOutcome.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ResourceDestroyBuildingOutcome {
    return ResourceDestroyBuildingOutcome.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


