// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { LevelRequirement } from "./level_requirement_type";
// Mark import as potentially unused
declare type __keep_LevelRequirement = LevelRequirement;
import { ToolRequirement } from "./tool_requirement_type";
// Mark import as potentially unused
declare type __keep_ToolRequirement = ToolRequirement;
import { InputItemStack } from "./input_item_stack_type";
// Mark import as potentially unused
declare type __keep_InputItemStack = InputItemStack;
import { ExperienceStackF32 } from "./experience_stack_f_32_type";
// Mark import as potentially unused
declare type __keep_ExperienceStackF32 = ExperienceStackF32;
import { Biome } from "./biome_type";
// Mark import as potentially unused
declare type __keep_Biome = Biome;


export type ResourcePlacementRecipeDesc = {
  id: number,
  name: string,
  timeRequirement: number,
  staminaRequirement: number,
  consumedResource: number,
  requiredInteriorTier: number,
  levelRequirements: LevelRequirement[],
  toolRequirements: ToolRequirement[],
  consumedItemStacks: InputItemStack[],
  consumedCargoStacks: InputItemStack[],
  experiencePerProgress: ExperienceStackF32[],
  discoveryTriggers: number[],
  requiredKnowledges: number[],
  requiredClaimTechId: number,
  requiredBiomes: Biome[],
  fullDiscoveryScore: number,
  toolMeshIndex: number,
  resourceDescriptionId: number,
  requiredPavingTier: number,
  actionsRequired: number,
  recipePerformanceId: number,
};
/**
 * An object for generated helper functions.
 */
export const ResourcePlacementRecipeDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "name", algebraicType: __AlgebraicTypeValue.String},
        { name: "timeRequirement", algebraicType: __AlgebraicTypeValue.F32},
        { name: "staminaRequirement", algebraicType: __AlgebraicTypeValue.F32},
        { name: "consumedResource", algebraicType: __AlgebraicTypeValue.I32},
        { name: "requiredInteriorTier", algebraicType: __AlgebraicTypeValue.I32},
        { name: "levelRequirements", algebraicType: __AlgebraicTypeValue.Array(LevelRequirement.getTypeScriptAlgebraicType())},
        { name: "toolRequirements", algebraicType: __AlgebraicTypeValue.Array(ToolRequirement.getTypeScriptAlgebraicType())},
        { name: "consumedItemStacks", algebraicType: __AlgebraicTypeValue.Array(InputItemStack.getTypeScriptAlgebraicType())},
        { name: "consumedCargoStacks", algebraicType: __AlgebraicTypeValue.Array(InputItemStack.getTypeScriptAlgebraicType())},
        { name: "experiencePerProgress", algebraicType: __AlgebraicTypeValue.Array(ExperienceStackF32.getTypeScriptAlgebraicType())},
        { name: "discoveryTriggers", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "requiredKnowledges", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.I32)},
        { name: "requiredClaimTechId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "requiredBiomes", algebraicType: __AlgebraicTypeValue.Array(Biome.getTypeScriptAlgebraicType())},
        { name: "fullDiscoveryScore", algebraicType: __AlgebraicTypeValue.I32},
        { name: "toolMeshIndex", algebraicType: __AlgebraicTypeValue.I32},
        { name: "resourceDescriptionId", algebraicType: __AlgebraicTypeValue.I32},
        { name: "requiredPavingTier", algebraicType: __AlgebraicTypeValue.I32},
        { name: "actionsRequired", algebraicType: __AlgebraicTypeValue.I32},
        { name: "recipePerformanceId", algebraicType: __AlgebraicTypeValue.I32},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ResourcePlacementRecipeDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, ResourcePlacementRecipeDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ResourcePlacementRecipeDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, ResourcePlacementRecipeDesc.getTypeScriptAlgebraicType());
  },

}

export default ResourcePlacementRecipeDesc;


