// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { SingleResourceToClumpDesc } from "./single_resource_to_clump_desc_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `single_resource_to_clump_desc`.
 *
 * Obtain a handle from the [`singleResourceToClumpDesc`] property on [`RemoteTables`],
 * like `ctx.db.singleResourceToClumpDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.singleResourceToClumpDesc.on_insert(...)`.
 */
export class SingleResourceToClumpDescTableHandle {
  tableCache: __TableCache<SingleResourceToClumpDesc>;

  constructor(tableCache: __TableCache<SingleResourceToClumpDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<SingleResourceToClumpDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `resourceId` unique index on the table `single_resource_to_clump_desc`,
   * which allows point queries on the field of the same name
   * via the [`SingleResourceToClumpDescResourceIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.singleResourceToClumpDesc.resourceId().find(...)`.
   *
   * Get a handle on the `resourceId` unique index on the table `single_resource_to_clump_desc`.
   */
  resourceId = {
    // Find the subscribed row whose `resourceId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): SingleResourceToClumpDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.resourceId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `clumpId` unique index on the table `single_resource_to_clump_desc`,
   * which allows point queries on the field of the same name
   * via the [`SingleResourceToClumpDescClumpIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.singleResourceToClumpDesc.clumpId().find(...)`.
   *
   * Get a handle on the `clumpId` unique index on the table `single_resource_to_clump_desc`.
   */
  clumpId = {
    // Find the subscribed row whose `clumpId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): SingleResourceToClumpDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.clumpId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: SingleResourceToClumpDesc, newRow: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: SingleResourceToClumpDesc, newRow: SingleResourceToClumpDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
