// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type SpawnInfo = {
  biomeIndex: bigint,
  chance: number,
  noiseOffsetX: number,
  noiseOffsetY: number,
  noiseThresholdBottom: number,
  noiseThresholdTop: number,
  noiseScale: number,
  noiseOctaves: number,
  noisePersistance: number,
  noiseLacunarity: number,
  spawnsOnLand: boolean,
  landElevationMin: number,
  landElevationMax: number,
  spawnsInWater: boolean,
  waterDepthMin: number,
  waterDepthMax: number,
  spawnsOnUnevenTerrain: boolean,
};
/**
 * An object for generated helper functions.
 */
export const SpawnInfo = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "biomeIndex", algebraicType: __AlgebraicTypeValue.U64},
        { name: "chance", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseOffsetX", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseOffsetY", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseThresholdBottom", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseThresholdTop", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseScale", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseOctaves", algebraicType: __AlgebraicTypeValue.I32},
        { name: "noisePersistance", algebraicType: __AlgebraicTypeValue.F32},
        { name: "noiseLacunarity", algebraicType: __AlgebraicTypeValue.F32},
        { name: "spawnsOnLand", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "landElevationMin", algebraicType: __AlgebraicTypeValue.I16},
        { name: "landElevationMax", algebraicType: __AlgebraicTypeValue.I16},
        { name: "spawnsInWater", algebraicType: __AlgebraicTypeValue.Bool},
        { name: "waterDepthMin", algebraicType: __AlgebraicTypeValue.I16},
        { name: "waterDepthMax", algebraicType: __AlgebraicTypeValue.I16},
        { name: "spawnsOnUnevenTerrain", algebraicType: __AlgebraicTypeValue.Bool},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: SpawnInfo): void {
    __AlgebraicTypeValue.serializeValue(writer, SpawnInfo.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): SpawnInfo {
    return __AlgebraicTypeValue.deserializeValue(reader, SpawnInfo.getTypeScriptAlgebraicType());
  },

}

export default SpawnInfo;


