// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PlaceableInteractionDesc } from "./placeable_interaction_desc_type";
import { LevelRequirement as __LevelRequirement } from "./level_requirement_type";
import { ItemStack as __ItemStack } from "./item_stack_type";
import { ToolRequirement as __ToolRequirement } from "./tool_requirement_type";
import { InputItemStack as __InputItemStack } from "./input_item_stack_type";
import { ExperienceStackF32 as __ExperienceStackF32 } from "./experience_stack_f_32_type";
import { PlaceableGrowthOutcomeV2 as __PlaceableGrowthOutcomeV2 } from "./placeable_growth_outcome_v_2_type";
import { PlaceableSelfBuffChance as __PlaceableSelfBuffChance } from "./placeable_self_buff_chance_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `staged_placeable_interaction_desc`.
 *
 * Obtain a handle from the [`stagedPlaceableInteractionDesc`] property on [`RemoteTables`],
 * like `ctx.db.stagedPlaceableInteractionDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.stagedPlaceableInteractionDesc.on_insert(...)`.
 */
export class StagedPlaceableInteractionDescTableHandle {
  tableCache: TableCache<PlaceableInteractionDesc>;

  constructor(tableCache: TableCache<PlaceableInteractionDesc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PlaceableInteractionDesc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `staged_placeable_interaction_desc`,
   * which allows point queries on the field of the same name
   * via the [`StagedPlaceableInteractionDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.stagedPlaceableInteractionDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `staged_placeable_interaction_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): PlaceableInteractionDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: PlaceableInteractionDesc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PlaceableInteractionDesc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PlaceableInteractionDesc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PlaceableInteractionDesc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: PlaceableInteractionDesc, newRow: PlaceableInteractionDesc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: PlaceableInteractionDesc, newRow: PlaceableInteractionDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
