// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { StagedStaticDataV3 } from "./staged_static_data_v_3_type";
import { StaticDataUploadV3 } from "./static_data_upload_v_3_type";
// Mark import as potentially unused
declare type __keep_StaticDataUploadV3 = StaticDataUploadV3;

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `staged_static_data_v3`.
 *
 * Obtain a handle from the [`stagedStaticDataV3`] property on [`RemoteTables`],
 * like `ctx.db.stagedStaticDataV3`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.stagedStaticDataV3.on_insert(...)`.
 */
export class StagedStaticDataV3TableHandle {
  tableCache: __TableCache<StagedStaticDataV3>;

  constructor(tableCache: __TableCache<StagedStaticDataV3>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<StagedStaticDataV3> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `version` unique index on the table `staged_static_data_v3`,
   * which allows point queries on the field of the same name
   * via the [`StagedStaticDataV3VersionUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.stagedStaticDataV3.version().find(...)`.
   *
   * Get a handle on the `version` unique index on the table `staged_static_data_v3`.
   */
  version = {
    // Find the subscribed row whose `version` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): StagedStaticDataV3 | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.version, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: StagedStaticDataV3) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: StagedStaticDataV3) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: StagedStaticDataV3) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: StagedStaticDataV3) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: StagedStaticDataV3, newRow: StagedStaticDataV3) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: StagedStaticDataV3, newRow: StagedStaticDataV3) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
