// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::enemy_type_type::EnemyType;
use super::interior_spawn_desc_type::InteriorSpawnDesc;
use super::interior_spawn_type_type::InteriorSpawnType;
use super::npc_type_type::NpcType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `staged_interior_spawn_desc`.
///
/// Obtain a handle from the [`StagedInteriorSpawnDescTableAccess::staged_interior_spawn_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.staged_interior_spawn_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_interior_spawn_desc().on_insert(...)`.
pub struct StagedInteriorSpawnDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<InteriorSpawnDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `staged_interior_spawn_desc`.
pub struct StagedInteriorSpawnDescTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for StagedInteriorSpawnDescTableAccessor {
    type Row = InteriorSpawnDesc;
    type Handle<'db> = StagedInteriorSpawnDescTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.staged_interior_spawn_desc()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `staged_interior_spawn_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StagedInteriorSpawnDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StagedInteriorSpawnDescTableHandle`], which mediates access to the table `staged_interior_spawn_desc`.
    fn staged_interior_spawn_desc(&self) -> StagedInteriorSpawnDescTableHandle<'_>;
}

impl StagedInteriorSpawnDescTableAccess for super::RemoteTables {
    fn staged_interior_spawn_desc(&self) -> StagedInteriorSpawnDescTableHandle<'_> {
        StagedInteriorSpawnDescTableHandle {
            imp: self
                .imp
                .get_table::<InteriorSpawnDesc>("staged_interior_spawn_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StagedInteriorSpawnDescInsertCallbackId(__sdk::CallbackId);
pub struct StagedInteriorSpawnDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for StagedInteriorSpawnDescTableHandle<'ctx> {
    type Row = InteriorSpawnDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InteriorSpawnDesc> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for StagedInteriorSpawnDescTableHandle<'ctx> {
    type Row = InteriorSpawnDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InteriorSpawnDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StagedInteriorSpawnDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescInsertCallbackId {
        StagedInteriorSpawnDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StagedInteriorSpawnDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StagedInteriorSpawnDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescDeleteCallbackId {
        StagedInteriorSpawnDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StagedInteriorSpawnDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for StagedInteriorSpawnDescTableHandle<'ctx> {
    type InsertCallbackId = StagedInteriorSpawnDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescInsertCallbackId {
        StagedInteriorSpawnDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StagedInteriorSpawnDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for StagedInteriorSpawnDescTableHandle<'ctx> {
    type DeleteCallbackId = StagedInteriorSpawnDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescDeleteCallbackId {
        StagedInteriorSpawnDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StagedInteriorSpawnDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct StagedInteriorSpawnDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StagedInteriorSpawnDescTableHandle<'ctx> {
    type UpdateCallbackId = StagedInteriorSpawnDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescUpdateCallbackId {
        StagedInteriorSpawnDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StagedInteriorSpawnDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for StagedInteriorSpawnDescTableHandle<'ctx> {
    type UpdateCallbackId = StagedInteriorSpawnDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StagedInteriorSpawnDescUpdateCallbackId {
        StagedInteriorSpawnDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StagedInteriorSpawnDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `staged_interior_spawn_desc`,
/// which allows point queries on the field of the same name
/// via the [`StagedInteriorSpawnDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_interior_spawn_desc().id().find(...)`.
pub struct StagedInteriorSpawnDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InteriorSpawnDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StagedInteriorSpawnDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `staged_interior_spawn_desc`.
    pub fn id(&self) -> StagedInteriorSpawnDescIdUnique<'ctx> {
        StagedInteriorSpawnDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StagedInteriorSpawnDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<InteriorSpawnDesc> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InteriorSpawnDesc>("staged_interior_spawn_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InteriorSpawnDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InteriorSpawnDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InteriorSpawnDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait staged_interior_spawn_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InteriorSpawnDesc`.
    fn staged_interior_spawn_desc(&self) -> __sdk::__query_builder::Table<InteriorSpawnDesc>;
}

impl staged_interior_spawn_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn staged_interior_spawn_desc(&self) -> __sdk::__query_builder::Table<InteriorSpawnDesc> {
        __sdk::__query_builder::Table::new("staged_interior_spawn_desc")
    }
}
