// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::storage_log_cleanup_loop_timer_type::StorageLogCleanupLoopTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StorageLogCleanupLoopArgs {
    pub timer: StorageLogCleanupLoopTimer,
}

impl From<StorageLogCleanupLoopArgs> for super::Reducer {
    fn from(args: StorageLogCleanupLoopArgs) -> Self {
        Self::StorageLogCleanupLoop { timer: args.timer }
    }
}

impl __sdk::InModule for StorageLogCleanupLoopArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `storage_log_cleanup_loop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait storage_log_cleanup_loop {
    /// Request that the remote module invoke the reducer `storage_log_cleanup_loop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`storage_log_cleanup_loop:storage_log_cleanup_loop_then`] to run a callback after the reducer completes.
    fn storage_log_cleanup_loop(&self, timer: StorageLogCleanupLoopTimer) -> __sdk::Result<()> {
        self.storage_log_cleanup_loop_then(timer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `storage_log_cleanup_loop` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn storage_log_cleanup_loop_then(
        &self,
        timer: StorageLogCleanupLoopTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl storage_log_cleanup_loop for super::RemoteReducers {
    fn storage_log_cleanup_loop_then(
        &self,
        timer: StorageLogCleanupLoopTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StorageLogCleanupLoopArgs { timer }, callback)
    }
}
