// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { TradeSessionStatus } from "./trade_session_status_type";
// Mark import as potentially unused
declare type __keep_TradeSessionStatus = TradeSessionStatus;
import { TradePocket } from "./trade_pocket_type";
// Mark import as potentially unused
declare type __keep_TradePocket = TradePocket;


export type TradeSessionState = {
  entityId: bigint,
  status: TradeSessionStatus,
  initiatorEntityId: bigint,
  acceptorEntityId: bigint,
  initiatorOffer: TradePocket[],
  acceptorOffer: TradePocket[],
  updatedAt: __Timestamp,
  resolutionMessage: string,
};
/**
 * An object for generated helper functions.
 */
export const TradeSessionState = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "entityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "status", algebraicType: TradeSessionStatus.getTypeScriptAlgebraicType()},
        { name: "initiatorEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "acceptorEntityId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "initiatorOffer", algebraicType: __AlgebraicTypeValue.Array(TradePocket.getTypeScriptAlgebraicType())},
        { name: "acceptorOffer", algebraicType: __AlgebraicTypeValue.Array(TradePocket.getTypeScriptAlgebraicType())},
        { name: "updatedAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "resolutionMessage", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: TradeSessionState): void {
    __AlgebraicTypeValue.serializeValue(writer, TradeSessionState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TradeSessionState {
    return __AlgebraicTypeValue.deserializeValue(reader, TradeSessionState.getTypeScriptAlgebraicType());
  },

}

export default TradeSessionState;


