// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ItemStack } from "./item_stack_type";
// Mark import as potentially unused
declare type __keep_ItemStack = ItemStack;
import { ExperienceStackF32 } from "./experience_stack_f_32_type";
// Mark import as potentially unused
declare type __keep_ExperienceStackF32 = ExperienceStackF32;
import { CappedLevelRequirement } from "./capped_level_requirement_type";
// Mark import as potentially unused
declare type __keep_CappedLevelRequirement = CappedLevelRequirement;


export type TravelerTaskDesc = {
  id: number,
  levelRequirement: CappedLevelRequirement,
  requiredItems: ItemStack[],
  rewardedItems: ItemStack[],
  rewardedExperience: ExperienceStackF32,
  description: string,
};
/**
 * An object for generated helper functions.
 */
export const TravelerTaskDesc = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.I32},
        { name: "levelRequirement", algebraicType: CappedLevelRequirement.getTypeScriptAlgebraicType()},
        { name: "requiredItems", algebraicType: __AlgebraicTypeValue.Array(ItemStack.getTypeScriptAlgebraicType())},
        { name: "rewardedItems", algebraicType: __AlgebraicTypeValue.Array(ItemStack.getTypeScriptAlgebraicType())},
        { name: "rewardedExperience", algebraicType: ExperienceStackF32.getTypeScriptAlgebraicType()},
        { name: "description", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: TravelerTaskDesc): void {
    __AlgebraicTypeValue.serializeValue(writer, TravelerTaskDesc.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): TravelerTaskDesc {
    return __AlgebraicTypeValue.deserializeValue(reader, TravelerTaskDesc.getTypeScriptAlgebraicType());
  },

}

export default TravelerTaskDesc;


