// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { UserAuthenticationState } from "./user_authentication_state_type";
// Mark import as potentially unused
declare type __keep_UserAuthenticationState = UserAuthenticationState;

import * as UserAuthenticationStateOpVariants from './user_authentication_state_op_variants'

// The tagged union or sum type for the algebraic type `UserAuthenticationStateOp`.
export type UserAuthenticationStateOp = UserAuthenticationStateOpVariants.Insert |
  UserAuthenticationStateOpVariants.Delete;

// A value with helper functions to construct the type.
export const UserAuthenticationStateOp = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Insert: (value: UserAuthenticationState): UserAuthenticationStateOp => ({ tag: "Insert", value }),
  Delete: (value: UserAuthenticationState): UserAuthenticationStateOp => ({ tag: "Delete", value }),

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Insert", algebraicType: UserAuthenticationState.getTypeScriptAlgebraicType() },
        { name: "Delete", algebraicType: UserAuthenticationState.getTypeScriptAlgebraicType() },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: UserAuthenticationStateOp): void {
      __AlgebraicTypeValue.serializeValue(writer, UserAuthenticationStateOp.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UserAuthenticationStateOp {
      return __AlgebraicTypeValue.deserializeValue(reader, UserAuthenticationStateOp.getTypeScriptAlgebraicType());
  },

}

export default UserAuthenticationStateOp;


