// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import * as VfxAttachmentPointVariants from './vfx_attachment_point_variants'

// The tagged union or sum type for the algebraic type `VfxAttachmentPoint`.
export type VfxAttachmentPoint = VfxAttachmentPointVariants.Origin |
  VfxAttachmentPointVariants.Overhead |
  VfxAttachmentPointVariants.Head |
  VfxAttachmentPointVariants.Chest |
  VfxAttachmentPointVariants.MainHand |
  VfxAttachmentPointVariants.OffHand |
  VfxAttachmentPointVariants.BothHands |
  VfxAttachmentPointVariants.Feet;

// A value with helper functions to construct the type.
export const VfxAttachmentPoint = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Origin: { tag: "Origin" } as const,
  Overhead: { tag: "Overhead" } as const,
  Head: { tag: "Head" } as const,
  Chest: { tag: "Chest" } as const,
  MainHand: { tag: "MainHand" } as const,
  OffHand: { tag: "OffHand" } as const,
  BothHands: { tag: "BothHands" } as const,
  Feet: { tag: "Feet" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Sum({
      variants: [
        { name: "Origin", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Overhead", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Head", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Chest", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "MainHand", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "OffHand", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "BothHands", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
        { name: "Feet", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: VfxAttachmentPoint): void {
      __AlgebraicTypeValue.serializeValue(writer, VfxAttachmentPoint.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): VfxAttachmentPoint {
      return __AlgebraicTypeValue.deserializeValue(reader, VfxAttachmentPoint.getTypeScriptAlgebraicType());
  },

}

export default VfxAttachmentPoint;


